//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import umontreal.iro.lecuyer.contactcenters.app.params.ServiceLevelParams;
import umontreal.iro.lecuyer.xmlbind.params.BooleanArray;
import umontreal.iro.lecuyer.xmlbind.params.PropertiesParams;
import umontreal.iro.lecuyer.xmlbind.params.RandomVariateGenParams;
import umontreal.iro.lecuyer.xmlbind.params.TimeUnitParam;


/**
 * 
 *             Specifies the common as well as call-type specific
 *             parameters for a blend and multi-skill call center model.
 *             These include random variate generators for service times,
 *             patience times and arrivals as well as information on the
 *             routing. This complex type defines attributes for encoding
 *             the simple information such as the number and duration of
 *             main periods in the model, the default time unit, etc.
 *             Nested elements are used for more complex information such
 *             as the description of a call type, an agent group, and
 *             routing parameters.
 *          
 * 
 * <p>Java class for CallCenterParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallCenterParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{http://www.iro.umontreal.ca/lecuyer/ssj}PropertiesParams" minOccurs="0"/>
 *         &lt;element name="busynessGen" type="{http://www.iro.umontreal.ca/lecuyer/ssj}RandomVariateGenParams" minOccurs="0"/>
 *         &lt;element name="defaultArrivalProcess" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}ArrivalProcessParams" minOccurs="0"/>
 *         &lt;element name="inboundType" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}InboundTypeParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="arrivalProcess" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}ArrivalProcessParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outboundType" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}OutboundTypeParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dialer" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}DialerParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="agentGroup" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}AgentGroupParams" maxOccurs="unbounded"/>
 *         &lt;element name="shiftMatrix" type="{http://www.iro.umontreal.ca/lecuyer/ssj}BooleanArray" minOccurs="0"/>
 *         &lt;element name="shift" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}ScheduleShiftParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="router" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}RouterParams"/>
 *         &lt;element name="startingState" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}StartingStateParams" minOccurs="0"/>
 *         &lt;element name="serviceLevel" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/app}ServiceLevelParams" maxOccurs="unbounded"/>
 *         &lt;element name="inboundTypeSegment" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}SegmentParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outboundTypeSegment" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}SegmentParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="callTypeSegment" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}SegmentParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="agentGroupSegment" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}SegmentParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="periodSegment" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}SegmentParams" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="defaultUnit" type="{http://www.iro.umontreal.ca/lecuyer/ssj}TimeUnitParam" default="HOUR" />
 *       &lt;attribute name="queueCapacity" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeInt" />
 *       &lt;attribute name="numPeriods" use="required" type="{http://www.iro.umontreal.ca/lecuyer/ssj}positiveInt" />
 *       &lt;attribute name="periodDuration" use="required" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDuration" />
 *       &lt;attribute name="startingDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="startingTime" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDuration" />
 *       &lt;attribute name="arrivalsMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="patienceTimesMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="serviceTimesMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="conferenceTimesMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="preServiceTimesNoConfMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="transferTimesMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="previewTimesMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="convertSchedulesToStaffing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="agentsMult" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeDouble" default="1" />
 *       &lt;attribute name="waitingTimePredictorClass" type="{http://www.w3.org/2001/XMLSchema}string" default="LastWaitingTimePredictor" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallCenterParams", propOrder = {
    "properties",
    "busynessGen",
    "defaultArrivalProcess",
    "inboundTypes",
    "arrivalProcesses",
    "outboundTypes",
    "dialers",
    "agentGroups",
    "shiftMatrix",
    "shifts",
    "router",
    "startingState",
    "serviceLevelParams",
    "inboundTypeSegments",
    "outboundTypeSegments",
    "callTypeSegments",
    "agentGroupSegments",
    "periodSegments"
})
public class CallCenterParams {

    protected PropertiesParams properties;
    protected RandomVariateGenParams busynessGen;
    protected ArrivalProcessParams defaultArrivalProcess;
    @XmlElement(name = "inboundType")
    protected List<InboundTypeParams> inboundTypes;
    @XmlElement(name = "arrivalProcess")
    protected List<ArrivalProcessParams> arrivalProcesses;
    @XmlElement(name = "outboundType")
    protected List<OutboundTypeParams> outboundTypes;
    @XmlElement(name = "dialer")
    protected List<DialerParams> dialers;
    @XmlElement(name = "agentGroup", required = true)
    protected List<AgentGroupParams> agentGroups;
    protected BooleanArray shiftMatrix;
    @XmlElement(name = "shift")
    protected List<ScheduleShiftParams> shifts;
    @XmlElement(required = true)
    protected RouterParams router;
    protected StartingStateParams startingState;
    @XmlElement(name = "serviceLevel", required = true)
    protected List<ServiceLevelParams> serviceLevelParams;
    @XmlElement(name = "inboundTypeSegment")
    protected List<SegmentParams> inboundTypeSegments;
    @XmlElement(name = "outboundTypeSegment")
    protected List<SegmentParams> outboundTypeSegments;
    @XmlElement(name = "callTypeSegment")
    protected List<SegmentParams> callTypeSegments;
    @XmlElement(name = "agentGroupSegment")
    protected List<SegmentParams> agentGroupSegments;
    @XmlElement(name = "periodSegment")
    protected List<SegmentParams> periodSegments;
    @XmlAttribute(name = "defaultUnit")
    protected TimeUnitParam defaultUnit;
    @XmlAttribute(name = "queueCapacity")
    protected Integer queueCapacity;
    @XmlAttribute(name = "numPeriods", required = true)
    protected int numPeriods;
    @XmlAttribute(name = "periodDuration", required = true)
    protected Duration periodDuration;
    @XmlAttribute(name = "startingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startingDate;
    @XmlAttribute(name = "startingTime")
    protected Duration startingTime;
    @XmlAttribute(name = "arrivalsMult")
    protected Double arrivalsMult;
    @XmlAttribute(name = "patienceTimesMult")
    protected Double patienceTimesMult;
    @XmlAttribute(name = "serviceTimesMult")
    protected Double serviceTimesMult;
    @XmlAttribute(name = "conferenceTimesMult")
    protected Double conferenceTimesMult;
    @XmlAttribute(name = "preServiceTimesNoConfMult")
    protected Double preServiceTimesNoConfMult;
    @XmlAttribute(name = "transferTimesMult")
    protected Double transferTimesMult;
    @XmlAttribute(name = "previewTimesMult")
    protected Double previewTimesMult;
    @XmlAttribute(name = "convertSchedulesToStaffing")
    protected Boolean convertSchedulesToStaffing;
    @XmlAttribute(name = "agentsMult")
    protected Double agentsMult;
    @XmlAttribute(name = "waitingTimePredictorClass")
    protected String waitingTimePredictorClass;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesParams }
     *     
     */
    public PropertiesParams getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesParams }
     *     
     */
    public void setProperties(PropertiesParams value) {
        this.properties = value;
    }

    public boolean isSetProperties() {
        return (this.properties!= null);
    }

    /**
     * Gets the value of the busynessGen property.
     * 
     * @return
     *     possible object is
     *     {@link RandomVariateGenParams }
     *     
     */
    public RandomVariateGenParams getBusynessGen() {
        return busynessGen;
    }

    /**
     * Sets the value of the busynessGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link RandomVariateGenParams }
     *     
     */
    public void setBusynessGen(RandomVariateGenParams value) {
        this.busynessGen = value;
    }

    public boolean isSetBusynessGen() {
        return (this.busynessGen!= null);
    }

    /**
     * Gets the value of the defaultArrivalProcess property.
     * 
     * @return
     *     possible object is
     *     {@link ArrivalProcessParams }
     *     
     */
    public ArrivalProcessParams getDefaultArrivalProcess() {
        return defaultArrivalProcess;
    }

    /**
     * Sets the value of the defaultArrivalProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrivalProcessParams }
     *     
     */
    public void setDefaultArrivalProcess(ArrivalProcessParams value) {
        this.defaultArrivalProcess = value;
    }

    public boolean isSetDefaultArrivalProcess() {
        return (this.defaultArrivalProcess!= null);
    }

    /**
     * Gets the value of the inboundTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inboundTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInboundTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InboundTypeParams }
     * 
     * 
     */
    public List<InboundTypeParams> getInboundTypes() {
        if (inboundTypes == null) {
            inboundTypes = new ArrayList<InboundTypeParams>();
        }
        return this.inboundTypes;
    }

    public boolean isSetInboundTypes() {
        return ((this.inboundTypes!= null)&&(!this.inboundTypes.isEmpty()));
    }

    public void unsetInboundTypes() {
        this.inboundTypes = null;
    }

    /**
     * Gets the value of the arrivalProcesses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrivalProcesses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrivalProcesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArrivalProcessParams }
     * 
     * 
     */
    public List<ArrivalProcessParams> getArrivalProcesses() {
        if (arrivalProcesses == null) {
            arrivalProcesses = new ArrayList<ArrivalProcessParams>();
        }
        return this.arrivalProcesses;
    }

    public boolean isSetArrivalProcesses() {
        return ((this.arrivalProcesses!= null)&&(!this.arrivalProcesses.isEmpty()));
    }

    public void unsetArrivalProcesses() {
        this.arrivalProcesses = null;
    }

    /**
     * Gets the value of the outboundTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outboundTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutboundTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutboundTypeParams }
     * 
     * 
     */
    public List<OutboundTypeParams> getOutboundTypes() {
        if (outboundTypes == null) {
            outboundTypes = new ArrayList<OutboundTypeParams>();
        }
        return this.outboundTypes;
    }

    public boolean isSetOutboundTypes() {
        return ((this.outboundTypes!= null)&&(!this.outboundTypes.isEmpty()));
    }

    public void unsetOutboundTypes() {
        this.outboundTypes = null;
    }

    /**
     * Gets the value of the dialers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dialers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDialers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DialerParams }
     * 
     * 
     */
    public List<DialerParams> getDialers() {
        if (dialers == null) {
            dialers = new ArrayList<DialerParams>();
        }
        return this.dialers;
    }

    public boolean isSetDialers() {
        return ((this.dialers!= null)&&(!this.dialers.isEmpty()));
    }

    public void unsetDialers() {
        this.dialers = null;
    }

    /**
     * Gets the value of the agentGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentGroupParams }
     * 
     * 
     */
    public List<AgentGroupParams> getAgentGroups() {
        if (agentGroups == null) {
            agentGroups = new ArrayList<AgentGroupParams>();
        }
        return this.agentGroups;
    }

    public boolean isSetAgentGroups() {
        return ((this.agentGroups!= null)&&(!this.agentGroups.isEmpty()));
    }

    public void unsetAgentGroups() {
        this.agentGroups = null;
    }

    /**
     * Gets the value of the shiftMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanArray }
     *     
     */
    public BooleanArray getShiftMatrix() {
        return shiftMatrix;
    }

    /**
     * Sets the value of the shiftMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanArray }
     *     
     */
    public void setShiftMatrix(BooleanArray value) {
        this.shiftMatrix = value;
    }

    public boolean isSetShiftMatrix() {
        return (this.shiftMatrix!= null);
    }

    /**
     * Gets the value of the shifts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shifts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShifts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduleShiftParams }
     * 
     * 
     */
    public List<ScheduleShiftParams> getShifts() {
        if (shifts == null) {
            shifts = new ArrayList<ScheduleShiftParams>();
        }
        return this.shifts;
    }

    public boolean isSetShifts() {
        return ((this.shifts!= null)&&(!this.shifts.isEmpty()));
    }

    public void unsetShifts() {
        this.shifts = null;
    }

    /**
     * Gets the value of the router property.
     * 
     * @return
     *     possible object is
     *     {@link RouterParams }
     *     
     */
    public RouterParams getRouter() {
        return router;
    }

    /**
     * Sets the value of the router property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouterParams }
     *     
     */
    public void setRouter(RouterParams value) {
        this.router = value;
    }

    public boolean isSetRouter() {
        return (this.router!= null);
    }

    /**
     * Gets the value of the startingState property.
     * 
     * @return
     *     possible object is
     *     {@link StartingStateParams }
     *     
     */
    public StartingStateParams getStartingState() {
        return startingState;
    }

    /**
     * Sets the value of the startingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartingStateParams }
     *     
     */
    public void setStartingState(StartingStateParams value) {
        this.startingState = value;
    }

    public boolean isSetStartingState() {
        return (this.startingState!= null);
    }

    /**
     * Gets the value of the serviceLevelParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceLevelParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceLevelParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceLevelParams }
     * 
     * 
     */
    public List<ServiceLevelParams> getServiceLevelParams() {
        if (serviceLevelParams == null) {
            serviceLevelParams = new ArrayList<ServiceLevelParams>();
        }
        return this.serviceLevelParams;
    }

    public boolean isSetServiceLevelParams() {
        return ((this.serviceLevelParams!= null)&&(!this.serviceLevelParams.isEmpty()));
    }

    public void unsetServiceLevelParams() {
        this.serviceLevelParams = null;
    }

    /**
     * Gets the value of the inboundTypeSegments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inboundTypeSegments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInboundTypeSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentParams }
     * 
     * 
     */
    public List<SegmentParams> getInboundTypeSegments() {
        if (inboundTypeSegments == null) {
            inboundTypeSegments = new ArrayList<SegmentParams>();
        }
        return this.inboundTypeSegments;
    }

    public boolean isSetInboundTypeSegments() {
        return ((this.inboundTypeSegments!= null)&&(!this.inboundTypeSegments.isEmpty()));
    }

    public void unsetInboundTypeSegments() {
        this.inboundTypeSegments = null;
    }

    /**
     * Gets the value of the outboundTypeSegments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outboundTypeSegments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutboundTypeSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentParams }
     * 
     * 
     */
    public List<SegmentParams> getOutboundTypeSegments() {
        if (outboundTypeSegments == null) {
            outboundTypeSegments = new ArrayList<SegmentParams>();
        }
        return this.outboundTypeSegments;
    }

    public boolean isSetOutboundTypeSegments() {
        return ((this.outboundTypeSegments!= null)&&(!this.outboundTypeSegments.isEmpty()));
    }

    public void unsetOutboundTypeSegments() {
        this.outboundTypeSegments = null;
    }

    /**
     * Gets the value of the callTypeSegments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the callTypeSegments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCallTypeSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentParams }
     * 
     * 
     */
    public List<SegmentParams> getCallTypeSegments() {
        if (callTypeSegments == null) {
            callTypeSegments = new ArrayList<SegmentParams>();
        }
        return this.callTypeSegments;
    }

    public boolean isSetCallTypeSegments() {
        return ((this.callTypeSegments!= null)&&(!this.callTypeSegments.isEmpty()));
    }

    public void unsetCallTypeSegments() {
        this.callTypeSegments = null;
    }

    /**
     * Gets the value of the agentGroupSegments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentGroupSegments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentGroupSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentParams }
     * 
     * 
     */
    public List<SegmentParams> getAgentGroupSegments() {
        if (agentGroupSegments == null) {
            agentGroupSegments = new ArrayList<SegmentParams>();
        }
        return this.agentGroupSegments;
    }

    public boolean isSetAgentGroupSegments() {
        return ((this.agentGroupSegments!= null)&&(!this.agentGroupSegments.isEmpty()));
    }

    public void unsetAgentGroupSegments() {
        this.agentGroupSegments = null;
    }

    /**
     * Gets the value of the periodSegments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodSegments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentParams }
     * 
     * 
     */
    public List<SegmentParams> getPeriodSegments() {
        if (periodSegments == null) {
            periodSegments = new ArrayList<SegmentParams>();
        }
        return this.periodSegments;
    }

    public boolean isSetPeriodSegments() {
        return ((this.periodSegments!= null)&&(!this.periodSegments.isEmpty()));
    }

    public void unsetPeriodSegments() {
        this.periodSegments = null;
    }

    /**
     * Gets the value of the defaultUnit property.
     * 
     * @return
     *     possible object is
     *     {@link TimeUnitParam }
     *     
     */
    public TimeUnitParam getDefaultUnit() {
        if (defaultUnit == null) {
            return TimeUnitParam.HOUR;
        } else {
            return defaultUnit;
        }
    }

    /**
     * Sets the value of the defaultUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeUnitParam }
     *     
     */
    public void setDefaultUnit(TimeUnitParam value) {
        this.defaultUnit = value;
    }

    public boolean isSetDefaultUnit() {
        return (this.defaultUnit!= null);
    }

    /**
     * Gets the value of the queueCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getQueueCapacity() {
        return queueCapacity;
    }

    /**
     * Sets the value of the queueCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQueueCapacity(int value) {
        this.queueCapacity = value;
    }

    public boolean isSetQueueCapacity() {
        return (this.queueCapacity!= null);
    }

    public void unsetQueueCapacity() {
        this.queueCapacity = null;
    }

    /**
     * Gets the value of the numPeriods property.
     * 
     */
    public int getNumPeriods() {
        return numPeriods;
    }

    /**
     * Sets the value of the numPeriods property.
     * 
     */
    public void setNumPeriods(int value) {
        this.numPeriods = value;
    }

    public boolean isSetNumPeriods() {
        return true;
    }

    /**
     * Gets the value of the periodDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getPeriodDuration() {
        return periodDuration;
    }

    /**
     * Sets the value of the periodDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPeriodDuration(Duration value) {
        this.periodDuration = value;
    }

    public boolean isSetPeriodDuration() {
        return (this.periodDuration!= null);
    }

    /**
     * Gets the value of the startingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartingDate() {
        return startingDate;
    }

    /**
     * Sets the value of the startingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartingDate(XMLGregorianCalendar value) {
        this.startingDate = value;
    }

    public boolean isSetStartingDate() {
        return (this.startingDate!= null);
    }

    /**
     * Gets the value of the startingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getStartingTime() {
        return startingTime;
    }

    /**
     * Sets the value of the startingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setStartingTime(Duration value) {
        this.startingTime = value;
    }

    public boolean isSetStartingTime() {
        return (this.startingTime!= null);
    }

    /**
     * Gets the value of the arrivalsMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getArrivalsMult() {
        if (arrivalsMult == null) {
            return  1.0D;
        } else {
            return arrivalsMult;
        }
    }

    /**
     * Sets the value of the arrivalsMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArrivalsMult(double value) {
        this.arrivalsMult = value;
    }

    public boolean isSetArrivalsMult() {
        return (this.arrivalsMult!= null);
    }

    public void unsetArrivalsMult() {
        this.arrivalsMult = null;
    }

    /**
     * Gets the value of the patienceTimesMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPatienceTimesMult() {
        if (patienceTimesMult == null) {
            return  1.0D;
        } else {
            return patienceTimesMult;
        }
    }

    /**
     * Sets the value of the patienceTimesMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPatienceTimesMult(double value) {
        this.patienceTimesMult = value;
    }

    public boolean isSetPatienceTimesMult() {
        return (this.patienceTimesMult!= null);
    }

    public void unsetPatienceTimesMult() {
        this.patienceTimesMult = null;
    }

    /**
     * Gets the value of the serviceTimesMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getServiceTimesMult() {
        if (serviceTimesMult == null) {
            return  1.0D;
        } else {
            return serviceTimesMult;
        }
    }

    /**
     * Sets the value of the serviceTimesMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setServiceTimesMult(double value) {
        this.serviceTimesMult = value;
    }

    public boolean isSetServiceTimesMult() {
        return (this.serviceTimesMult!= null);
    }

    public void unsetServiceTimesMult() {
        this.serviceTimesMult = null;
    }

    /**
     * Gets the value of the conferenceTimesMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getConferenceTimesMult() {
        if (conferenceTimesMult == null) {
            return  1.0D;
        } else {
            return conferenceTimesMult;
        }
    }

    /**
     * Sets the value of the conferenceTimesMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConferenceTimesMult(double value) {
        this.conferenceTimesMult = value;
    }

    public boolean isSetConferenceTimesMult() {
        return (this.conferenceTimesMult!= null);
    }

    public void unsetConferenceTimesMult() {
        this.conferenceTimesMult = null;
    }

    /**
     * Gets the value of the preServiceTimesNoConfMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPreServiceTimesNoConfMult() {
        if (preServiceTimesNoConfMult == null) {
            return  1.0D;
        } else {
            return preServiceTimesNoConfMult;
        }
    }

    /**
     * Sets the value of the preServiceTimesNoConfMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPreServiceTimesNoConfMult(double value) {
        this.preServiceTimesNoConfMult = value;
    }

    public boolean isSetPreServiceTimesNoConfMult() {
        return (this.preServiceTimesNoConfMult!= null);
    }

    public void unsetPreServiceTimesNoConfMult() {
        this.preServiceTimesNoConfMult = null;
    }

    /**
     * Gets the value of the transferTimesMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getTransferTimesMult() {
        if (transferTimesMult == null) {
            return  1.0D;
        } else {
            return transferTimesMult;
        }
    }

    /**
     * Sets the value of the transferTimesMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransferTimesMult(double value) {
        this.transferTimesMult = value;
    }

    public boolean isSetTransferTimesMult() {
        return (this.transferTimesMult!= null);
    }

    public void unsetTransferTimesMult() {
        this.transferTimesMult = null;
    }

    /**
     * Gets the value of the previewTimesMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPreviewTimesMult() {
        if (previewTimesMult == null) {
            return  1.0D;
        } else {
            return previewTimesMult;
        }
    }

    /**
     * Sets the value of the previewTimesMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPreviewTimesMult(double value) {
        this.previewTimesMult = value;
    }

    public boolean isSetPreviewTimesMult() {
        return (this.previewTimesMult!= null);
    }

    public void unsetPreviewTimesMult() {
        this.previewTimesMult = null;
    }

    /**
     * Gets the value of the convertSchedulesToStaffing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConvertSchedulesToStaffing() {
        if (convertSchedulesToStaffing == null) {
            return false;
        } else {
            return convertSchedulesToStaffing;
        }
    }

    /**
     * Sets the value of the convertSchedulesToStaffing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConvertSchedulesToStaffing(boolean value) {
        this.convertSchedulesToStaffing = value;
    }

    public boolean isSetConvertSchedulesToStaffing() {
        return (this.convertSchedulesToStaffing!= null);
    }

    public void unsetConvertSchedulesToStaffing() {
        this.convertSchedulesToStaffing = null;
    }

    /**
     * Gets the value of the agentsMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getAgentsMult() {
        if (agentsMult == null) {
            return  1.0D;
        } else {
            return agentsMult;
        }
    }

    /**
     * Sets the value of the agentsMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAgentsMult(double value) {
        this.agentsMult = value;
    }

    public boolean isSetAgentsMult() {
        return (this.agentsMult!= null);
    }

    public void unsetAgentsMult() {
        this.agentsMult = null;
    }

    /**
     * Gets the value of the waitingTimePredictorClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaitingTimePredictorClass() {
        if (waitingTimePredictorClass == null) {
            return "LastWaitingTimePredictor";
        } else {
            return waitingTimePredictorClass;
        }
    }

    /**
     * Sets the value of the waitingTimePredictorClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaitingTimePredictorClass(String value) {
        this.waitingTimePredictorClass = value;
    }

    public boolean isSetWaitingTimePredictorClass() {
        return (this.waitingTimePredictorClass!= null);
    }

}
