//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * 
 *                   Parameters for the dialer, for blend/multi-skill call
 *                   center.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DialerParams", propOrder = {
    "minFreeAgentsTest",
    "minFreeAgentsTarget",
    "dialerLimit",
    "agentGroupInfo"
})
public class DialerParams
    extends CallSourceParams
{

    @XmlList
    @XmlElement(type = Integer.class)
    protected int[] minFreeAgentsTest;
    @XmlList
    @XmlElement(type = Integer.class)
    protected int[] minFreeAgentsTarget;
    protected umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[] dialerLimit;
    protected List<DialerAgentGroupParams> agentGroupInfo;
    @XmlAttribute(name = "dialerPolicy", required = true)
    protected String dialerPolicy;
    @XmlAttribute(name = "dropMismatches")
    protected Boolean dropMismatches;
    @XmlAttribute(name = "preventMismatches")
    protected Boolean preventMismatches;
    @XmlAttribute(name = "kappa")
    protected Double kappa;
    @XmlAttribute(name = "c")
    protected Integer c;
    @XmlAttribute(name = "maxBadCallRate")
    protected Double maxBadCallRate;
    @XmlAttribute(name = "mismatchRateThresh")
    protected Double mismatchRateThresh;
    @XmlAttribute(name = "numCheckedPeriods")
    protected Integer numCheckedPeriods;
    @XmlAttribute(name = "checkedPeriodDuration")
    protected Duration checkedPeriodDuration;
    @XmlAttribute(name = "serviceLevelIndex")
    protected Integer serviceLevelIndex;
    @XmlAttribute(name = "slInboundThresh")
    protected Double slInboundThresh;
    @XmlAttribute(name = "slOutboundThresh")
    protected Double slOutboundThresh;
    @XmlAttribute(name = "useNumActionEvents")
    protected Boolean useNumActionEvents;
    @XmlAttribute(name = "useRoutingMatrix")
    protected Boolean useRoutingMatrix;

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Integer }
     *     
     */
    public int[] getMinFreeAgentsTest() {
        if (this.minFreeAgentsTest == null) {
            return new int[ 0 ] ;
        }
        int[] retVal = new int[this.minFreeAgentsTest.length] ;
        System.arraycopy(this.minFreeAgentsTest, 0, retVal, 0, this.minFreeAgentsTest.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Integer }
     *     
     */
    public int getMinFreeAgentsTest(int idx) {
        if (this.minFreeAgentsTest == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.minFreeAgentsTest[idx];
    }

    public int getMinFreeAgentsTestLength() {
        if (this.minFreeAgentsTest == null) {
            return  0;
        }
        return this.minFreeAgentsTest.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Integer }
     *     
     */
    public void setMinFreeAgentsTest(int[] values) {
        int len = values.length;
        this.minFreeAgentsTest = ((int[]) new int[len] );
        for (int i = 0; (i<len); i ++) {
            this.minFreeAgentsTest[i] = new Integer(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public int setMinFreeAgentsTest(int idx, int value) {
        return this.minFreeAgentsTest[idx] = new Integer(value);
    }

    public boolean isSetMinFreeAgentsTest() {
        return ((this.minFreeAgentsTest!= null)&&(this.minFreeAgentsTest.length > 0));
    }

    public void unsetMinFreeAgentsTest() {
        this.minFreeAgentsTest = null;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Integer }
     *     
     */
    public int[] getMinFreeAgentsTarget() {
        if (this.minFreeAgentsTarget == null) {
            return new int[ 0 ] ;
        }
        int[] retVal = new int[this.minFreeAgentsTarget.length] ;
        System.arraycopy(this.minFreeAgentsTarget, 0, retVal, 0, this.minFreeAgentsTarget.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Integer }
     *     
     */
    public int getMinFreeAgentsTarget(int idx) {
        if (this.minFreeAgentsTarget == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.minFreeAgentsTarget[idx];
    }

    public int getMinFreeAgentsTargetLength() {
        if (this.minFreeAgentsTarget == null) {
            return  0;
        }
        return this.minFreeAgentsTarget.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Integer }
     *     
     */
    public void setMinFreeAgentsTarget(int[] values) {
        int len = values.length;
        this.minFreeAgentsTarget = ((int[]) new int[len] );
        for (int i = 0; (i<len); i ++) {
            this.minFreeAgentsTarget[i] = new Integer(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public int setMinFreeAgentsTarget(int idx, int value) {
        return this.minFreeAgentsTarget[idx] = new Integer(value);
    }

    public boolean isSetMinFreeAgentsTarget() {
        return ((this.minFreeAgentsTarget!= null)&&(this.minFreeAgentsTarget.length > 0));
    }

    public void unsetMinFreeAgentsTarget() {
        this.minFreeAgentsTarget = null;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams }
     *     
     */
    public umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[] getDialerLimit() {
        if (this.dialerLimit == null) {
            return new umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[ 0 ] ;
        }
        umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[] retVal = new umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[this.dialerLimit.length] ;
        System.arraycopy(this.dialerLimit, 0, retVal, 0, this.dialerLimit.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams }
     *     
     */
    public umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams getDialerLimit(int idx) {
        if (this.dialerLimit == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.dialerLimit[idx];
    }

    public int getDialerLimitLength() {
        if (this.dialerLimit == null) {
            return  0;
        }
        return this.dialerLimit.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams }
     *     
     */
    public void setDialerLimit(umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[] values) {
        int len = values.length;
        this.dialerLimit = ((umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[]) new umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams[len] );
        for (int i = 0; (i<len); i ++) {
            this.dialerLimit[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams }
     *     
     */
    public umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams setDialerLimit(int idx, umontreal.iro.lecuyer.contactcenters.msk.params.DialerLimitParams value) {
        return this.dialerLimit[idx] = value;
    }

    public boolean isSetDialerLimit() {
        return ((this.dialerLimit!= null)&&(this.dialerLimit.length > 0));
    }

    public void unsetDialerLimit() {
        this.dialerLimit = null;
    }

    /**
     * Gets the value of the agentGroupInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentGroupInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentGroupInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DialerAgentGroupParams }
     * 
     * 
     */
    public List<DialerAgentGroupParams> getAgentGroupInfo() {
        if (agentGroupInfo == null) {
            agentGroupInfo = new ArrayList<DialerAgentGroupParams>();
        }
        return this.agentGroupInfo;
    }

    public boolean isSetAgentGroupInfo() {
        return ((this.agentGroupInfo!= null)&&(!this.agentGroupInfo.isEmpty()));
    }

    public void unsetAgentGroupInfo() {
        this.agentGroupInfo = null;
    }

    /**
     * Gets the value of the dialerPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialerPolicy() {
        return dialerPolicy;
    }

    /**
     * Sets the value of the dialerPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialerPolicy(String value) {
        this.dialerPolicy = value;
    }

    public boolean isSetDialerPolicy() {
        return (this.dialerPolicy!= null);
    }

    /**
     * Gets the value of the dropMismatches property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDropMismatches() {
        if (dropMismatches == null) {
            return false;
        } else {
            return dropMismatches;
        }
    }

    /**
     * Sets the value of the dropMismatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropMismatches(boolean value) {
        this.dropMismatches = value;
    }

    public boolean isSetDropMismatches() {
        return (this.dropMismatches!= null);
    }

    public void unsetDropMismatches() {
        this.dropMismatches = null;
    }

    /**
     * Gets the value of the preventMismatches property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPreventMismatches() {
        if (preventMismatches == null) {
            return false;
        } else {
            return preventMismatches;
        }
    }

    /**
     * Sets the value of the preventMismatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreventMismatches(boolean value) {
        this.preventMismatches = value;
    }

    public boolean isSetPreventMismatches() {
        return (this.preventMismatches!= null);
    }

    public void unsetPreventMismatches() {
        this.preventMismatches = null;
    }

    /**
     * Gets the value of the kappa property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getKappa() {
        if (kappa == null) {
            return  1.0D;
        } else {
            return kappa;
        }
    }

    /**
     * Sets the value of the kappa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKappa(double value) {
        this.kappa = value;
    }

    public boolean isSetKappa() {
        return (this.kappa!= null);
    }

    public void unsetKappa() {
        this.kappa = null;
    }

    /**
     * Gets the value of the c property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getC() {
        if (c == null) {
            return  0;
        } else {
            return c;
        }
    }

    /**
     * Sets the value of the c property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setC(int value) {
        this.c = value;
    }

    public boolean isSetC() {
        return (this.c!= null);
    }

    public void unsetC() {
        this.c = null;
    }

    /**
     * Gets the value of the maxBadCallRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getMaxBadCallRate() {
        return maxBadCallRate;
    }

    /**
     * Sets the value of the maxBadCallRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxBadCallRate(double value) {
        this.maxBadCallRate = value;
    }

    public boolean isSetMaxBadCallRate() {
        return (this.maxBadCallRate!= null);
    }

    public void unsetMaxBadCallRate() {
        this.maxBadCallRate = null;
    }

    /**
     * Gets the value of the mismatchRateThresh property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getMismatchRateThresh() {
        return mismatchRateThresh;
    }

    /**
     * Sets the value of the mismatchRateThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMismatchRateThresh(double value) {
        this.mismatchRateThresh = value;
    }

    public boolean isSetMismatchRateThresh() {
        return (this.mismatchRateThresh!= null);
    }

    public void unsetMismatchRateThresh() {
        this.mismatchRateThresh = null;
    }

    /**
     * Gets the value of the numCheckedPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumCheckedPeriods() {
        return numCheckedPeriods;
    }

    /**
     * Sets the value of the numCheckedPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumCheckedPeriods(int value) {
        this.numCheckedPeriods = value;
    }

    public boolean isSetNumCheckedPeriods() {
        return (this.numCheckedPeriods!= null);
    }

    public void unsetNumCheckedPeriods() {
        this.numCheckedPeriods = null;
    }

    /**
     * Gets the value of the checkedPeriodDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getCheckedPeriodDuration() {
        return checkedPeriodDuration;
    }

    /**
     * Sets the value of the checkedPeriodDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setCheckedPeriodDuration(Duration value) {
        this.checkedPeriodDuration = value;
    }

    public boolean isSetCheckedPeriodDuration() {
        return (this.checkedPeriodDuration!= null);
    }

    /**
     * Gets the value of the serviceLevelIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getServiceLevelIndex() {
        if (serviceLevelIndex == null) {
            return  0;
        } else {
            return serviceLevelIndex;
        }
    }

    /**
     * Sets the value of the serviceLevelIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceLevelIndex(int value) {
        this.serviceLevelIndex = value;
    }

    public boolean isSetServiceLevelIndex() {
        return (this.serviceLevelIndex!= null);
    }

    public void unsetServiceLevelIndex() {
        this.serviceLevelIndex = null;
    }

    /**
     * Gets the value of the slInboundThresh property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getSlInboundThresh() {
        if (slInboundThresh == null) {
            return  0.7D;
        } else {
            return slInboundThresh;
        }
    }

    /**
     * Sets the value of the slInboundThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSlInboundThresh(double value) {
        this.slInboundThresh = value;
    }

    public boolean isSetSlInboundThresh() {
        return (this.slInboundThresh!= null);
    }

    public void unsetSlInboundThresh() {
        this.slInboundThresh = null;
    }

    /**
     * Gets the value of the slOutboundThresh property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getSlOutboundThresh() {
        return slOutboundThresh;
    }

    /**
     * Sets the value of the slOutboundThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSlOutboundThresh(double value) {
        this.slOutboundThresh = value;
    }

    public boolean isSetSlOutboundThresh() {
        return (this.slOutboundThresh!= null);
    }

    public void unsetSlOutboundThresh() {
        this.slOutboundThresh = null;
    }

    /**
     * Gets the value of the useNumActionEvents property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseNumActionEvents() {
        if (useNumActionEvents == null) {
            return true;
        } else {
            return useNumActionEvents;
        }
    }

    /**
     * Sets the value of the useNumActionEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseNumActionEvents(boolean value) {
        this.useNumActionEvents = value;
    }

    public boolean isSetUseNumActionEvents() {
        return (this.useNumActionEvents!= null);
    }

    public void unsetUseNumActionEvents() {
        this.useNumActionEvents = null;
    }

    /**
     * Gets the value of the useRoutingMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseRoutingMatrix() {
        if (useRoutingMatrix == null) {
            return true;
        } else {
            return useRoutingMatrix;
        }
    }

    /**
     * Sets the value of the useRoutingMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseRoutingMatrix(boolean value) {
        this.useRoutingMatrix = value;
    }

    public boolean isSetUseRoutingMatrix() {
        return (this.useRoutingMatrix!= null);
    }

    public void unsetUseRoutingMatrix() {
        this.useRoutingMatrix = null;
    }

}
