//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import umontreal.iro.lecuyer.xmlbind.params.Named;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the umontreal.iro.lecuyer.contactcenters.msk.params package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSKCCParams_QNAME = new QName("http://www.iro.umontreal.ca/lecuyer/contactcenters/msk", "MSKCCParams");
    private final static QName _ConditionParamsListAll_QNAME = new QName("", "all");
    private final static QName _ConditionParamsListQueueSizeThresh_QNAME = new QName("", "queueSizeThresh");
    private final static QName _ConditionParamsListFracBusyAgentsThresh_QNAME = new QName("", "fracBusyAgentsThresh");
    private final static QName _ConditionParamsListEither_QNAME = new QName("", "either");
    private final static QName _ConditionParamsListStat_QNAME = new QName("", "stat");
    private final static QName _ConditionParamsListNumFreeAgentsThresh_QNAME = new QName("", "numFreeAgentsThresh");
    private final static QName _ConditionParamsListCustom_QNAME = new QName("", "custom");
    private final static QName _ConditionParamsListFracBusyAgents_QNAME = new QName("", "fracBusyAgents");
    private final static QName _ConditionParamsListNumFreeAgents_QNAME = new QName("", "numFreeAgents");
    private final static QName _ConditionParamsListQueueSizes_QNAME = new QName("", "queueSizes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: umontreal.iro.lecuyer.contactcenters.msk.params
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CallCenterParams }
     * 
     */
    public CallCenterParams createCallCenterParams() {
        return new CallCenterParams();
    }

    /**
     * Create an instance of {@link ServiceTimeParams }
     * 
     */
    public ServiceTimeParams createServiceTimeParams() {
        return new ServiceTimeParams();
    }

    /**
     * Create an instance of {@link SegmentParams }
     * 
     */
    public SegmentParams createSegmentParams() {
        return new SegmentParams();
    }

    /**
     * Create an instance of {@link AgentParams }
     * 
     */
    public AgentParams createAgentParams() {
        return new AgentParams();
    }

    /**
     * Create an instance of {@link RoutingStageParams }
     * 
     */
    public RoutingStageParams createRoutingStageParams() {
        return new RoutingStageParams();
    }

    /**
     * Create an instance of {@link DetailedWaitingCall }
     * 
     */
    public DetailedWaitingCall createDetailedWaitingCall() {
        return new DetailedWaitingCall();
    }

    /**
     * Create an instance of {@link IndexThreshIntParams }
     * 
     */
    public IndexThreshIntParams createIndexThreshIntParams() {
        return new IndexThreshIntParams();
    }

    /**
     * Create an instance of {@link ProducedCallTypeParams }
     * 
     */
    public ProducedCallTypeParams createProducedCallTypeParams() {
        return new ProducedCallTypeParams();
    }

    /**
     * Create an instance of {@link DetailedServingCall }
     * 
     */
    public DetailedServingCall createDetailedServingCall() {
        return new DetailedServingCall();
    }

    /**
     * Create an instance of {@link DefaultCaseParams }
     * 
     */
    public DefaultCaseParams createDefaultCaseParams() {
        return new DefaultCaseParams();
    }

    /**
     * Create an instance of {@link DetailedStartingGroupState }
     * 
     */
    public DetailedStartingGroupState createDetailedStartingGroupState() {
        return new DetailedStartingGroupState();
    }

    /**
     * Create an instance of {@link RoutingCaseParams }
     * 
     */
    public RoutingCaseParams createRoutingCaseParams() {
        return new RoutingCaseParams();
    }

    /**
     * Create an instance of {@link ConditionParamsList }
     * 
     */
    public ConditionParamsList createConditionParamsList() {
        return new ConditionParamsList();
    }

    /**
     * Create an instance of {@link AgentGroupScheduleParams }
     * 
     */
    public AgentGroupScheduleParams createAgentGroupScheduleParams() {
        return new AgentGroupScheduleParams();
    }

    /**
     * Create an instance of {@link CallTypeRoutingParams }
     * 
     */
    public CallTypeRoutingParams createCallTypeRoutingParams() {
        return new CallTypeRoutingParams();
    }

    /**
     * Create an instance of {@link StatConditionParams }
     * 
     */
    public StatConditionParams createStatConditionParams() {
        return new StatConditionParams();
    }

    /**
     * Create an instance of {@link ShiftPartParams }
     * 
     */
    public ShiftPartParams createShiftPartParams() {
        return new ShiftPartParams();
    }

    /**
     * Create an instance of {@link InboundTypeParams }
     * 
     */
    public InboundTypeParams createInboundTypeParams() {
        return new InboundTypeParams();
    }

    /**
     * Create an instance of {@link ArrivalProcessParams }
     * 
     */
    public ArrivalProcessParams createArrivalProcessParams() {
        return new ArrivalProcessParams();
    }

    /**
     * Create an instance of {@link TwoIndicesParams }
     * 
     */
    public TwoIndicesParams createTwoIndicesParams() {
        return new TwoIndicesParams();
    }

    /**
     * Create an instance of {@link DialerAgentGroupParams }
     * 
     */
    public DialerAgentGroupParams createDialerAgentGroupParams() {
        return new DialerAgentGroupParams();
    }

    /**
     * Create an instance of {@link DialerParams }
     * 
     */
    public DialerParams createDialerParams() {
        return new DialerParams();
    }

    /**
     * Create an instance of {@link ScheduleShiftParams }
     * 
     */
    public ScheduleShiftParams createScheduleShiftParams() {
        return new ScheduleShiftParams();
    }

    /**
     * Create an instance of {@link OutboundTypeParams }
     * 
     */
    public OutboundTypeParams createOutboundTypeParams() {
        return new OutboundTypeParams();
    }

    /**
     * Create an instance of {@link IndexThreshIntWithTypeParams }
     * 
     */
    public IndexThreshIntWithTypeParams createIndexThreshIntWithTypeParams() {
        return new IndexThreshIntWithTypeParams();
    }

    /**
     * Create an instance of {@link TimeIntervalParams }
     * 
     */
    public TimeIntervalParams createTimeIntervalParams() {
        return new TimeIntervalParams();
    }

    /**
     * Create an instance of {@link TwoIndicesWithTypesParams }
     * 
     */
    public TwoIndicesWithTypesParams createTwoIndicesWithTypesParams() {
        return new TwoIndicesWithTypesParams();
    }

    /**
     * Create an instance of {@link DetailedStartingQueueState }
     * 
     */
    public DetailedStartingQueueState createDetailedStartingQueueState() {
        return new DetailedStartingQueueState();
    }

    /**
     * Create an instance of {@link IndexThreshParams }
     * 
     */
    public IndexThreshParams createIndexThreshParams() {
        return new IndexThreshParams();
    }

    /**
     * Create an instance of {@link RoutingTableSources }
     * 
     */
    public RoutingTableSources createRoutingTableSources() {
        return new RoutingTableSources();
    }

    /**
     * Create an instance of {@link AgentGroupParams }
     * 
     */
    public AgentGroupParams createAgentGroupParams() {
        return new AgentGroupParams();
    }

    /**
     * Create an instance of {@link RouterParams }
     * 
     */
    public RouterParams createRouterParams() {
        return new RouterParams();
    }

    /**
     * Create an instance of {@link DoubleArrayWithMinWaitingTime }
     * 
     */
    public DoubleArrayWithMinWaitingTime createDoubleArrayWithMinWaitingTime() {
        return new DoubleArrayWithMinWaitingTime();
    }

    /**
     * Create an instance of {@link IndexThreshWithTypeParams }
     * 
     */
    public IndexThreshWithTypeParams createIndexThreshWithTypeParams() {
        return new IndexThreshWithTypeParams();
    }

    /**
     * Create an instance of {@link StartingStateParams }
     * 
     */
    public StartingStateParams createStartingStateParams() {
        return new StartingStateParams();
    }

    /**
     * Create an instance of {@link ConditionParams }
     * 
     */
    public ConditionParams createConditionParams() {
        return new ConditionParams();
    }

    /**
     * Create an instance of {@link AgentGroupIndex }
     * 
     */
    public AgentGroupIndex createAgentGroupIndex() {
        return new AgentGroupIndex();
    }

    /**
     * Create an instance of {@link DialerLimitParams }
     * 
     */
    public DialerLimitParams createDialerLimitParams() {
        return new DialerLimitParams();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallCenterParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iro.umontreal.ca/lecuyer/contactcenters/msk", name = "MSKCCParams")
    public JAXBElement<CallCenterParams> createMSKCCParams(CallCenterParams value) {
        return new JAXBElement<CallCenterParams>(_MSKCCParams_QNAME, CallCenterParams.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionParamsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "all", scope = ConditionParamsList.class)
    public JAXBElement<ConditionParamsList> createConditionParamsListAll(ConditionParamsList value) {
        return new JAXBElement<ConditionParamsList>(_ConditionParamsListAll_QNAME, ConditionParamsList.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexThreshIntWithTypeParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queueSizeThresh", scope = ConditionParamsList.class)
    public JAXBElement<IndexThreshIntWithTypeParams> createConditionParamsListQueueSizeThresh(IndexThreshIntWithTypeParams value) {
        return new JAXBElement<IndexThreshIntWithTypeParams>(_ConditionParamsListQueueSizeThresh_QNAME, IndexThreshIntWithTypeParams.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexThreshWithTypeParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fracBusyAgentsThresh", scope = ConditionParamsList.class)
    public JAXBElement<IndexThreshWithTypeParams> createConditionParamsListFracBusyAgentsThresh(IndexThreshWithTypeParams value) {
        return new JAXBElement<IndexThreshWithTypeParams>(_ConditionParamsListFracBusyAgentsThresh_QNAME, IndexThreshWithTypeParams.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionParamsList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "either", scope = ConditionParamsList.class)
    public JAXBElement<ConditionParamsList> createConditionParamsListEither(ConditionParamsList value) {
        return new JAXBElement<ConditionParamsList>(_ConditionParamsListEither_QNAME, ConditionParamsList.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatConditionParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stat", scope = ConditionParamsList.class)
    public JAXBElement<StatConditionParams> createConditionParamsListStat(StatConditionParams value) {
        return new JAXBElement<StatConditionParams>(_ConditionParamsListStat_QNAME, StatConditionParams.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexThreshIntParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numFreeAgentsThresh", scope = ConditionParamsList.class)
    public JAXBElement<IndexThreshIntParams> createConditionParamsListNumFreeAgentsThresh(IndexThreshIntParams value) {
        return new JAXBElement<IndexThreshIntParams>(_ConditionParamsListNumFreeAgentsThresh_QNAME, IndexThreshIntParams.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Named }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "custom", scope = ConditionParamsList.class)
    public JAXBElement<Named> createConditionParamsListCustom(Named value) {
        return new JAXBElement<Named>(_ConditionParamsListCustom_QNAME, Named.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TwoIndicesWithTypesParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fracBusyAgents", scope = ConditionParamsList.class)
    public JAXBElement<TwoIndicesWithTypesParams> createConditionParamsListFracBusyAgents(TwoIndicesWithTypesParams value) {
        return new JAXBElement<TwoIndicesWithTypesParams>(_ConditionParamsListFracBusyAgents_QNAME, TwoIndicesWithTypesParams.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TwoIndicesParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numFreeAgents", scope = ConditionParamsList.class)
    public JAXBElement<TwoIndicesParams> createConditionParamsListNumFreeAgents(TwoIndicesParams value) {
        return new JAXBElement<TwoIndicesParams>(_ConditionParamsListNumFreeAgents_QNAME, TwoIndicesParams.class, ConditionParamsList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TwoIndicesWithTypesParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queueSizes", scope = ConditionParamsList.class)
    public JAXBElement<TwoIndicesWithTypesParams> createConditionParamsListQueueSizes(TwoIndicesWithTypesParams value) {
        return new JAXBElement<TwoIndicesWithTypesParams>(_ConditionParamsListQueueSizes_QNAME, TwoIndicesWithTypesParams.class, ConditionParamsList.class, value);
    }

}
