//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import umontreal.iro.lecuyer.contactcenters.params.MultiPeriodGenParams;


/**
 * 
 *                   Defines the parameters for an outbound call type, for
 *                   blend/multi-skill call center.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutboundTypeParams", propOrder = {
    "probReach",
    "reachTime",
    "failTime",
    "probRPC",
    "previewTimes",
    "dialer"
})
public class OutboundTypeParams
    extends CallTypeParams
{

    @XmlList
    @XmlElement(type = Double.class)
    protected double[] probReach;
    protected MultiPeriodGenParams reachTime;
    protected MultiPeriodGenParams failTime;
    @XmlList
    @XmlElement(type = Double.class)
    protected double[] probRPC;
    @XmlElement(name = "previewTime")
    protected List<ServiceTimeParams> previewTimes;
    protected DialerParams dialer;
    @XmlAttribute(name = "previewTimesMult")
    protected Double previewTimesMult;

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Double }
     *     
     */
    public double[] getProbReach() {
        if (this.probReach == null) {
            return new double[ 0 ] ;
        }
        double[] retVal = new double[this.probReach.length] ;
        System.arraycopy(this.probReach, 0, retVal, 0, this.probReach.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Double }
     *     
     */
    public double getProbReach(int idx) {
        if (this.probReach == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.probReach[idx];
    }

    public int getProbReachLength() {
        if (this.probReach == null) {
            return  0;
        }
        return this.probReach.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Double }
     *     
     */
    public void setProbReach(double[] values) {
        int len = values.length;
        this.probReach = ((double[]) new double[len] );
        for (int i = 0; (i<len); i ++) {
            this.probReach[i] = new Double(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public double setProbReach(int idx, double value) {
        return this.probReach[idx] = new Double(value);
    }

    public boolean isSetProbReach() {
        return ((this.probReach!= null)&&(this.probReach.length > 0));
    }

    public void unsetProbReach() {
        this.probReach = null;
    }

    /**
     * Gets the value of the reachTime property.
     * 
     * @return
     *     possible object is
     *     {@link MultiPeriodGenParams }
     *     
     */
    public MultiPeriodGenParams getReachTime() {
        return reachTime;
    }

    /**
     * Sets the value of the reachTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiPeriodGenParams }
     *     
     */
    public void setReachTime(MultiPeriodGenParams value) {
        this.reachTime = value;
    }

    public boolean isSetReachTime() {
        return (this.reachTime!= null);
    }

    /**
     * Gets the value of the failTime property.
     * 
     * @return
     *     possible object is
     *     {@link MultiPeriodGenParams }
     *     
     */
    public MultiPeriodGenParams getFailTime() {
        return failTime;
    }

    /**
     * Sets the value of the failTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiPeriodGenParams }
     *     
     */
    public void setFailTime(MultiPeriodGenParams value) {
        this.failTime = value;
    }

    public boolean isSetFailTime() {
        return (this.failTime!= null);
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Double }
     *     
     */
    public double[] getProbRPC() {
        if (this.probRPC == null) {
            return new double[ 0 ] ;
        }
        double[] retVal = new double[this.probRPC.length] ;
        System.arraycopy(this.probRPC, 0, retVal, 0, this.probRPC.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Double }
     *     
     */
    public double getProbRPC(int idx) {
        if (this.probRPC == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.probRPC[idx];
    }

    public int getProbRPCLength() {
        if (this.probRPC == null) {
            return  0;
        }
        return this.probRPC.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Double }
     *     
     */
    public void setProbRPC(double[] values) {
        int len = values.length;
        this.probRPC = ((double[]) new double[len] );
        for (int i = 0; (i<len); i ++) {
            this.probRPC[i] = new Double(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public double setProbRPC(int idx, double value) {
        return this.probRPC[idx] = new Double(value);
    }

    public boolean isSetProbRPC() {
        return ((this.probRPC!= null)&&(this.probRPC.length > 0));
    }

    public void unsetProbRPC() {
        this.probRPC = null;
    }

    /**
     * Gets the value of the previewTimes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the previewTimes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreviewTimes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceTimeParams }
     * 
     * 
     */
    public List<ServiceTimeParams> getPreviewTimes() {
        if (previewTimes == null) {
            previewTimes = new ArrayList<ServiceTimeParams>();
        }
        return this.previewTimes;
    }

    public boolean isSetPreviewTimes() {
        return ((this.previewTimes!= null)&&(!this.previewTimes.isEmpty()));
    }

    public void unsetPreviewTimes() {
        this.previewTimes = null;
    }

    /**
     * Gets the value of the dialer property.
     * 
     * @return
     *     possible object is
     *     {@link DialerParams }
     *     
     */
    public DialerParams getDialer() {
        return dialer;
    }

    /**
     * Sets the value of the dialer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DialerParams }
     *     
     */
    public void setDialer(DialerParams value) {
        this.dialer = value;
    }

    public boolean isSetDialer() {
        return (this.dialer!= null);
    }

    /**
     * Gets the value of the previewTimesMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPreviewTimesMult() {
        if (previewTimesMult == null) {
            return  1.0D;
        } else {
            return previewTimesMult;
        }
    }

    /**
     * Sets the value of the previewTimesMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPreviewTimesMult(double value) {
        this.previewTimesMult = value;
    }

    public boolean isSetPreviewTimesMult() {
        return (this.previewTimesMult!= null);
    }

    public void unsetPreviewTimesMult() {
        this.previewTimesMult = null;
    }

}
