//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   Determines the parameters of a call type produced by a
 *                   call source.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProducedCallTypeParams", propOrder = {
    "probPeriod"
})
public class ProducedCallTypeParams {

    @XmlList
    @XmlElement(type = Double.class)
    protected double[] probPeriod;
    @XmlAttribute(name = "type", required = true)
    protected int type;
    @XmlAttribute(name = "probability")
    protected Double probability;

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Double }
     *     
     */
    public double[] getProbPeriod() {
        if (this.probPeriod == null) {
            return new double[ 0 ] ;
        }
        double[] retVal = new double[this.probPeriod.length] ;
        System.arraycopy(this.probPeriod, 0, retVal, 0, this.probPeriod.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Double }
     *     
     */
    public double getProbPeriod(int idx) {
        if (this.probPeriod == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.probPeriod[idx];
    }

    public int getProbPeriodLength() {
        if (this.probPeriod == null) {
            return  0;
        }
        return this.probPeriod.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Double }
     *     
     */
    public void setProbPeriod(double[] values) {
        int len = values.length;
        this.probPeriod = ((double[]) new double[len] );
        for (int i = 0; (i<len); i ++) {
            this.probPeriod[i] = new Double(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public double setProbPeriod(int idx, double value) {
        return this.probPeriod[idx] = new Double(value);
    }

    public boolean isSetProbPeriod() {
        return ((this.probPeriod!= null)&&(this.probPeriod.length > 0));
    }

    public void unsetProbPeriod() {
        this.probPeriod = null;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }

    public boolean isSetType() {
        return true;
    }

    /**
     * Gets the value of the probability property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getProbability() {
        if (probability == null) {
            return  1.0D;
        } else {
            return probability;
        }
    }

    /**
     * Sets the value of the probability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProbability(double value) {
        this.probability = value;
    }

    public boolean isSetProbability() {
        return (this.probability!= null);
    }

    public void unsetProbability() {
        this.probability = null;
    }

}
