//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             Determines how missing routing information can be inferred
 *             from alternative data structures. Often, a missing routing
 *             data structure can be created several ways. For example, the
 *             type-to-group map may be constructed using the group-to-type
 *             map, a matrix of ranks, etc. However, some algorithms
 *             destroy or guess information, which can lead to incorrect
 *             results. If this element is given without any attribute, the
 *             default most common constructions are used: a missing matrix
 *             of ranks or incidence matrix is obtained by transposing the
 *             given complementary matrix. Other mappings can be given by
 *             setting attributes in this element.
 *          
 * 
 * <p>Java class for RoutingTableSources complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutingTableSources">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="typeToGroupMap" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}TypeToGroupMapSource" />
 *       &lt;attribute name="groupToTypeMap" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}GroupToTypeMapSource" />
 *       &lt;attribute name="ranksTG" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}RanksTGSource" default="ranksGT" />
 *       &lt;attribute name="ranksGT" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}RanksGTSource" default="ranksTG" />
 *       &lt;attribute name="incidenceMatrixTG" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}IncidenceMatrixTGSource" default="incidenceMatrixGT" />
 *       &lt;attribute name="incidenceMatrixGT" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}IncidenceMatrixGTSource" default="incidenceMatrixTG" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutingTableSources")
public class RoutingTableSources {

    @XmlAttribute(name = "typeToGroupMap")
    protected TypeToGroupMapSource typeToGroupMap;
    @XmlAttribute(name = "groupToTypeMap")
    protected GroupToTypeMapSource groupToTypeMap;
    @XmlAttribute(name = "ranksTG")
    protected RanksTGSource ranksTG;
    @XmlAttribute(name = "ranksGT")
    protected RanksGTSource ranksGT;
    @XmlAttribute(name = "incidenceMatrixTG")
    protected IncidenceMatrixTGSource incidenceMatrixTG;
    @XmlAttribute(name = "incidenceMatrixGT")
    protected IncidenceMatrixGTSource incidenceMatrixGT;

    /**
     * Gets the value of the typeToGroupMap property.
     * 
     * @return
     *     possible object is
     *     {@link TypeToGroupMapSource }
     *     
     */
    public TypeToGroupMapSource getTypeToGroupMap() {
        return typeToGroupMap;
    }

    /**
     * Sets the value of the typeToGroupMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeToGroupMapSource }
     *     
     */
    public void setTypeToGroupMap(TypeToGroupMapSource value) {
        this.typeToGroupMap = value;
    }

    public boolean isSetTypeToGroupMap() {
        return (this.typeToGroupMap!= null);
    }

    /**
     * Gets the value of the groupToTypeMap property.
     * 
     * @return
     *     possible object is
     *     {@link GroupToTypeMapSource }
     *     
     */
    public GroupToTypeMapSource getGroupToTypeMap() {
        return groupToTypeMap;
    }

    /**
     * Sets the value of the groupToTypeMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupToTypeMapSource }
     *     
     */
    public void setGroupToTypeMap(GroupToTypeMapSource value) {
        this.groupToTypeMap = value;
    }

    public boolean isSetGroupToTypeMap() {
        return (this.groupToTypeMap!= null);
    }

    /**
     * Gets the value of the ranksTG property.
     * 
     * @return
     *     possible object is
     *     {@link RanksTGSource }
     *     
     */
    public RanksTGSource getRanksTG() {
        if (ranksTG == null) {
            return RanksTGSource.RANKS_GT;
        } else {
            return ranksTG;
        }
    }

    /**
     * Sets the value of the ranksTG property.
     * 
     * @param value
     *     allowed object is
     *     {@link RanksTGSource }
     *     
     */
    public void setRanksTG(RanksTGSource value) {
        this.ranksTG = value;
    }

    public boolean isSetRanksTG() {
        return (this.ranksTG!= null);
    }

    /**
     * Gets the value of the ranksGT property.
     * 
     * @return
     *     possible object is
     *     {@link RanksGTSource }
     *     
     */
    public RanksGTSource getRanksGT() {
        if (ranksGT == null) {
            return RanksGTSource.RANKS_TG;
        } else {
            return ranksGT;
        }
    }

    /**
     * Sets the value of the ranksGT property.
     * 
     * @param value
     *     allowed object is
     *     {@link RanksGTSource }
     *     
     */
    public void setRanksGT(RanksGTSource value) {
        this.ranksGT = value;
    }

    public boolean isSetRanksGT() {
        return (this.ranksGT!= null);
    }

    /**
     * Gets the value of the incidenceMatrixTG property.
     * 
     * @return
     *     possible object is
     *     {@link IncidenceMatrixTGSource }
     *     
     */
    public IncidenceMatrixTGSource getIncidenceMatrixTG() {
        if (incidenceMatrixTG == null) {
            return IncidenceMatrixTGSource.INCIDENCE_MATRIX_GT;
        } else {
            return incidenceMatrixTG;
        }
    }

    /**
     * Sets the value of the incidenceMatrixTG property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidenceMatrixTGSource }
     *     
     */
    public void setIncidenceMatrixTG(IncidenceMatrixTGSource value) {
        this.incidenceMatrixTG = value;
    }

    public boolean isSetIncidenceMatrixTG() {
        return (this.incidenceMatrixTG!= null);
    }

    /**
     * Gets the value of the incidenceMatrixGT property.
     * 
     * @return
     *     possible object is
     *     {@link IncidenceMatrixGTSource }
     *     
     */
    public IncidenceMatrixGTSource getIncidenceMatrixGT() {
        if (incidenceMatrixGT == null) {
            return IncidenceMatrixGTSource.INCIDENCE_MATRIX_TG;
        } else {
            return incidenceMatrixGT;
        }
    }

    /**
     * Sets the value of the incidenceMatrixGT property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidenceMatrixGTSource }
     *     
     */
    public void setIncidenceMatrixGT(IncidenceMatrixGTSource value) {
        this.incidenceMatrixGT = value;
    }

    public boolean isSetIncidenceMatrixGT() {
        return (this.incidenceMatrixGT!= null);
    }

}
