//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import umontreal.iro.lecuyer.xmlbind.params.BooleanArray;
import umontreal.iro.lecuyer.xmlbind.params.DoubleArray;
import umontreal.iro.lecuyer.xmlbind.params.IntArray;
import umontreal.iro.lecuyer.xmlbind.params.NonNegativeDurationArray;
import umontreal.iro.lecuyer.xmlbind.params.PropertiesParams;


/**
 * 
 *                   Represents the router's parameters for a
 *                   blend/multi-skill call center.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouterParams", propOrder = {
    "properties",
    "typeToGroupMap",
    "groupToTypeMap",
    "ranksTG",
    "ranksGT",
    "ranksGTUpdate",
    "weightsTG",
    "weightsGT",
    "delaysGT",
    "incidenceMatrixTG",
    "incidenceMatrixGT",
    "queueWeights",
    "skillCounts",
    "targetFracAgents",
    "targetQueueRatio",
    "routingTableSources",
    "callTypeRouting"
})
public class RouterParams {

    protected PropertiesParams properties;
    protected IntArray typeToGroupMap;
    protected IntArray groupToTypeMap;
    protected DoubleArray ranksTG;
    protected DoubleArray ranksGT;
    protected List<DoubleArrayWithMinWaitingTime> ranksGTUpdate;
    protected DoubleArray weightsTG;
    protected DoubleArray weightsGT;
    protected NonNegativeDurationArray delaysGT;
    protected BooleanArray incidenceMatrixTG;
    protected BooleanArray incidenceMatrixGT;
    @XmlList
    @XmlElement(type = Double.class)
    protected double[] queueWeights;
    @XmlList
    @XmlElement(type = Integer.class)
    protected int[] skillCounts;
    @XmlList
    @XmlElement(type = Double.class)
    protected double[] targetFracAgents;
    @XmlList
    @XmlElement(type = Double.class)
    protected double[] targetQueueRatio;
    protected RoutingTableSources routingTableSources;
    protected List<CallTypeRoutingParams> callTypeRouting;
    @XmlAttribute(name = "routerPolicy")
    protected String routerPolicy;
    @XmlAttribute(name = "localSpecOverflowDelay")
    protected Duration localSpecOverflowDelay;
    @XmlAttribute(name = "overflowTransfer")
    protected Boolean overflowTransfer;
    @XmlAttribute(name = "longestWaitingTime")
    protected Boolean longestWaitingTime;
    @XmlAttribute(name = "numTestingPeriods")
    protected Integer numTestingPeriods;
    @XmlAttribute(name = "testingPeriodDuration")
    protected Duration testingPeriodDuration;
    @XmlAttribute(name = "queueSizeThresh")
    protected Integer queueSizeThresh;
    @XmlAttribute(name = "allowCopies")
    protected Boolean allowCopies;
    @XmlAttribute(name = "randomizedAgentSelection")
    protected Boolean randomizedAgentSelection;
    @XmlAttribute(name = "randomizedContactSelection")
    protected Boolean randomizedContactSelection;
    @XmlAttribute(name = "agentSelectionScore")
    protected AgentSelectionScore agentSelectionScore;
    @XmlAttribute(name = "contactSelectionScore")
    protected ContactSelectionScore contactSelectionScore;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesParams }
     *     
     */
    public PropertiesParams getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesParams }
     *     
     */
    public void setProperties(PropertiesParams value) {
        this.properties = value;
    }

    public boolean isSetProperties() {
        return (this.properties!= null);
    }

    /**
     * Gets the value of the typeToGroupMap property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getTypeToGroupMap() {
        return typeToGroupMap;
    }

    /**
     * Sets the value of the typeToGroupMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setTypeToGroupMap(IntArray value) {
        this.typeToGroupMap = value;
    }

    public boolean isSetTypeToGroupMap() {
        return (this.typeToGroupMap!= null);
    }

    /**
     * Gets the value of the groupToTypeMap property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getGroupToTypeMap() {
        return groupToTypeMap;
    }

    /**
     * Sets the value of the groupToTypeMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setGroupToTypeMap(IntArray value) {
        this.groupToTypeMap = value;
    }

    public boolean isSetGroupToTypeMap() {
        return (this.groupToTypeMap!= null);
    }

    /**
     * Gets the value of the ranksTG property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleArray }
     *     
     */
    public DoubleArray getRanksTG() {
        return ranksTG;
    }

    /**
     * Sets the value of the ranksTG property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleArray }
     *     
     */
    public void setRanksTG(DoubleArray value) {
        this.ranksTG = value;
    }

    public boolean isSetRanksTG() {
        return (this.ranksTG!= null);
    }

    /**
     * Gets the value of the ranksGT property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleArray }
     *     
     */
    public DoubleArray getRanksGT() {
        return ranksGT;
    }

    /**
     * Sets the value of the ranksGT property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleArray }
     *     
     */
    public void setRanksGT(DoubleArray value) {
        this.ranksGT = value;
    }

    public boolean isSetRanksGT() {
        return (this.ranksGT!= null);
    }

    /**
     * Gets the value of the ranksGTUpdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ranksGTUpdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRanksGTUpdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DoubleArrayWithMinWaitingTime }
     * 
     * 
     */
    public List<DoubleArrayWithMinWaitingTime> getRanksGTUpdate() {
        if (ranksGTUpdate == null) {
            ranksGTUpdate = new ArrayList<DoubleArrayWithMinWaitingTime>();
        }
        return this.ranksGTUpdate;
    }

    public boolean isSetRanksGTUpdate() {
        return ((this.ranksGTUpdate!= null)&&(!this.ranksGTUpdate.isEmpty()));
    }

    public void unsetRanksGTUpdate() {
        this.ranksGTUpdate = null;
    }

    /**
     * Gets the value of the weightsTG property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleArray }
     *     
     */
    public DoubleArray getWeightsTG() {
        return weightsTG;
    }

    /**
     * Sets the value of the weightsTG property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleArray }
     *     
     */
    public void setWeightsTG(DoubleArray value) {
        this.weightsTG = value;
    }

    public boolean isSetWeightsTG() {
        return (this.weightsTG!= null);
    }

    /**
     * Gets the value of the weightsGT property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleArray }
     *     
     */
    public DoubleArray getWeightsGT() {
        return weightsGT;
    }

    /**
     * Sets the value of the weightsGT property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleArray }
     *     
     */
    public void setWeightsGT(DoubleArray value) {
        this.weightsGT = value;
    }

    public boolean isSetWeightsGT() {
        return (this.weightsGT!= null);
    }

    /**
     * Gets the value of the delaysGT property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeDurationArray }
     *     
     */
    public NonNegativeDurationArray getDelaysGT() {
        return delaysGT;
    }

    /**
     * Sets the value of the delaysGT property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeDurationArray }
     *     
     */
    public void setDelaysGT(NonNegativeDurationArray value) {
        this.delaysGT = value;
    }

    public boolean isSetDelaysGT() {
        return (this.delaysGT!= null);
    }

    /**
     * Gets the value of the incidenceMatrixTG property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanArray }
     *     
     */
    public BooleanArray getIncidenceMatrixTG() {
        return incidenceMatrixTG;
    }

    /**
     * Sets the value of the incidenceMatrixTG property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanArray }
     *     
     */
    public void setIncidenceMatrixTG(BooleanArray value) {
        this.incidenceMatrixTG = value;
    }

    public boolean isSetIncidenceMatrixTG() {
        return (this.incidenceMatrixTG!= null);
    }

    /**
     * Gets the value of the incidenceMatrixGT property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanArray }
     *     
     */
    public BooleanArray getIncidenceMatrixGT() {
        return incidenceMatrixGT;
    }

    /**
     * Sets the value of the incidenceMatrixGT property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanArray }
     *     
     */
    public void setIncidenceMatrixGT(BooleanArray value) {
        this.incidenceMatrixGT = value;
    }

    public boolean isSetIncidenceMatrixGT() {
        return (this.incidenceMatrixGT!= null);
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Double }
     *     
     */
    public double[] getQueueWeights() {
        if (this.queueWeights == null) {
            return new double[ 0 ] ;
        }
        double[] retVal = new double[this.queueWeights.length] ;
        System.arraycopy(this.queueWeights, 0, retVal, 0, this.queueWeights.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Double }
     *     
     */
    public double getQueueWeights(int idx) {
        if (this.queueWeights == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.queueWeights[idx];
    }

    public int getQueueWeightsLength() {
        if (this.queueWeights == null) {
            return  0;
        }
        return this.queueWeights.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Double }
     *     
     */
    public void setQueueWeights(double[] values) {
        int len = values.length;
        this.queueWeights = ((double[]) new double[len] );
        for (int i = 0; (i<len); i ++) {
            this.queueWeights[i] = new Double(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public double setQueueWeights(int idx, double value) {
        return this.queueWeights[idx] = new Double(value);
    }

    public boolean isSetQueueWeights() {
        return ((this.queueWeights!= null)&&(this.queueWeights.length > 0));
    }

    public void unsetQueueWeights() {
        this.queueWeights = null;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Integer }
     *     
     */
    public int[] getSkillCounts() {
        if (this.skillCounts == null) {
            return new int[ 0 ] ;
        }
        int[] retVal = new int[this.skillCounts.length] ;
        System.arraycopy(this.skillCounts, 0, retVal, 0, this.skillCounts.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Integer }
     *     
     */
    public int getSkillCounts(int idx) {
        if (this.skillCounts == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.skillCounts[idx];
    }

    public int getSkillCountsLength() {
        if (this.skillCounts == null) {
            return  0;
        }
        return this.skillCounts.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Integer }
     *     
     */
    public void setSkillCounts(int[] values) {
        int len = values.length;
        this.skillCounts = ((int[]) new int[len] );
        for (int i = 0; (i<len); i ++) {
            this.skillCounts[i] = new Integer(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public int setSkillCounts(int idx, int value) {
        return this.skillCounts[idx] = new Integer(value);
    }

    public boolean isSetSkillCounts() {
        return ((this.skillCounts!= null)&&(this.skillCounts.length > 0));
    }

    public void unsetSkillCounts() {
        this.skillCounts = null;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Double }
     *     
     */
    public double[] getTargetFracAgents() {
        if (this.targetFracAgents == null) {
            return new double[ 0 ] ;
        }
        double[] retVal = new double[this.targetFracAgents.length] ;
        System.arraycopy(this.targetFracAgents, 0, retVal, 0, this.targetFracAgents.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Double }
     *     
     */
    public double getTargetFracAgents(int idx) {
        if (this.targetFracAgents == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.targetFracAgents[idx];
    }

    public int getTargetFracAgentsLength() {
        if (this.targetFracAgents == null) {
            return  0;
        }
        return this.targetFracAgents.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Double }
     *     
     */
    public void setTargetFracAgents(double[] values) {
        int len = values.length;
        this.targetFracAgents = ((double[]) new double[len] );
        for (int i = 0; (i<len); i ++) {
            this.targetFracAgents[i] = new Double(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public double setTargetFracAgents(int idx, double value) {
        return this.targetFracAgents[idx] = new Double(value);
    }

    public boolean isSetTargetFracAgents() {
        return ((this.targetFracAgents!= null)&&(this.targetFracAgents.length > 0));
    }

    public void unsetTargetFracAgents() {
        this.targetFracAgents = null;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Double }
     *     
     */
    public double[] getTargetQueueRatio() {
        if (this.targetQueueRatio == null) {
            return new double[ 0 ] ;
        }
        double[] retVal = new double[this.targetQueueRatio.length] ;
        System.arraycopy(this.targetQueueRatio, 0, retVal, 0, this.targetQueueRatio.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Double }
     *     
     */
    public double getTargetQueueRatio(int idx) {
        if (this.targetQueueRatio == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.targetQueueRatio[idx];
    }

    public int getTargetQueueRatioLength() {
        if (this.targetQueueRatio == null) {
            return  0;
        }
        return this.targetQueueRatio.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Double }
     *     
     */
    public void setTargetQueueRatio(double[] values) {
        int len = values.length;
        this.targetQueueRatio = ((double[]) new double[len] );
        for (int i = 0; (i<len); i ++) {
            this.targetQueueRatio[i] = new Double(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public double setTargetQueueRatio(int idx, double value) {
        return this.targetQueueRatio[idx] = new Double(value);
    }

    public boolean isSetTargetQueueRatio() {
        return ((this.targetQueueRatio!= null)&&(this.targetQueueRatio.length > 0));
    }

    public void unsetTargetQueueRatio() {
        this.targetQueueRatio = null;
    }

    /**
     * Gets the value of the routingTableSources property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingTableSources }
     *     
     */
    public RoutingTableSources getRoutingTableSources() {
        return routingTableSources;
    }

    /**
     * Sets the value of the routingTableSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingTableSources }
     *     
     */
    public void setRoutingTableSources(RoutingTableSources value) {
        this.routingTableSources = value;
    }

    public boolean isSetRoutingTableSources() {
        return (this.routingTableSources!= null);
    }

    /**
     * Gets the value of the callTypeRouting property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the callTypeRouting property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCallTypeRouting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CallTypeRoutingParams }
     * 
     * 
     */
    public List<CallTypeRoutingParams> getCallTypeRouting() {
        if (callTypeRouting == null) {
            callTypeRouting = new ArrayList<CallTypeRoutingParams>();
        }
        return this.callTypeRouting;
    }

    public boolean isSetCallTypeRouting() {
        return ((this.callTypeRouting!= null)&&(!this.callTypeRouting.isEmpty()));
    }

    public void unsetCallTypeRouting() {
        this.callTypeRouting = null;
    }

    /**
     * Gets the value of the routerPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouterPolicy() {
        return routerPolicy;
    }

    /**
     * Sets the value of the routerPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouterPolicy(String value) {
        this.routerPolicy = value;
    }

    public boolean isSetRouterPolicy() {
        return (this.routerPolicy!= null);
    }

    /**
     * Gets the value of the localSpecOverflowDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getLocalSpecOverflowDelay() {
        return localSpecOverflowDelay;
    }

    /**
     * Sets the value of the localSpecOverflowDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setLocalSpecOverflowDelay(Duration value) {
        this.localSpecOverflowDelay = value;
    }

    public boolean isSetLocalSpecOverflowDelay() {
        return (this.localSpecOverflowDelay!= null);
    }

    /**
     * Gets the value of the overflowTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOverflowTransfer() {
        if (overflowTransfer == null) {
            return false;
        } else {
            return overflowTransfer;
        }
    }

    /**
     * Sets the value of the overflowTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverflowTransfer(boolean value) {
        this.overflowTransfer = value;
    }

    public boolean isSetOverflowTransfer() {
        return (this.overflowTransfer!= null);
    }

    public void unsetOverflowTransfer() {
        this.overflowTransfer = null;
    }

    /**
     * Gets the value of the longestWaitingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLongestWaitingTime() {
        if (longestWaitingTime == null) {
            return true;
        } else {
            return longestWaitingTime;
        }
    }

    /**
     * Sets the value of the longestWaitingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLongestWaitingTime(boolean value) {
        this.longestWaitingTime = value;
    }

    public boolean isSetLongestWaitingTime() {
        return (this.longestWaitingTime!= null);
    }

    public void unsetLongestWaitingTime() {
        this.longestWaitingTime = null;
    }

    /**
     * Gets the value of the numTestingPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumTestingPeriods() {
        return numTestingPeriods;
    }

    /**
     * Sets the value of the numTestingPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumTestingPeriods(int value) {
        this.numTestingPeriods = value;
    }

    public boolean isSetNumTestingPeriods() {
        return (this.numTestingPeriods!= null);
    }

    public void unsetNumTestingPeriods() {
        this.numTestingPeriods = null;
    }

    /**
     * Gets the value of the testingPeriodDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTestingPeriodDuration() {
        return testingPeriodDuration;
    }

    /**
     * Sets the value of the testingPeriodDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTestingPeriodDuration(Duration value) {
        this.testingPeriodDuration = value;
    }

    public boolean isSetTestingPeriodDuration() {
        return (this.testingPeriodDuration!= null);
    }

    /**
     * Gets the value of the queueSizeThresh property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getQueueSizeThresh() {
        return queueSizeThresh;
    }

    /**
     * Sets the value of the queueSizeThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQueueSizeThresh(int value) {
        this.queueSizeThresh = value;
    }

    public boolean isSetQueueSizeThresh() {
        return (this.queueSizeThresh!= null);
    }

    public void unsetQueueSizeThresh() {
        this.queueSizeThresh = null;
    }

    /**
     * Gets the value of the allowCopies property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowCopies() {
        if (allowCopies == null) {
            return true;
        } else {
            return allowCopies;
        }
    }

    /**
     * Sets the value of the allowCopies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowCopies(boolean value) {
        this.allowCopies = value;
    }

    public boolean isSetAllowCopies() {
        return (this.allowCopies!= null);
    }

    public void unsetAllowCopies() {
        this.allowCopies = null;
    }

    /**
     * Gets the value of the randomizedAgentSelection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRandomizedAgentSelection() {
        if (randomizedAgentSelection == null) {
            return false;
        } else {
            return randomizedAgentSelection;
        }
    }

    /**
     * Sets the value of the randomizedAgentSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRandomizedAgentSelection(boolean value) {
        this.randomizedAgentSelection = value;
    }

    public boolean isSetRandomizedAgentSelection() {
        return (this.randomizedAgentSelection!= null);
    }

    public void unsetRandomizedAgentSelection() {
        this.randomizedAgentSelection = null;
    }

    /**
     * Gets the value of the randomizedContactSelection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRandomizedContactSelection() {
        if (randomizedContactSelection == null) {
            return false;
        } else {
            return randomizedContactSelection;
        }
    }

    /**
     * Sets the value of the randomizedContactSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRandomizedContactSelection(boolean value) {
        this.randomizedContactSelection = value;
    }

    public boolean isSetRandomizedContactSelection() {
        return (this.randomizedContactSelection!= null);
    }

    public void unsetRandomizedContactSelection() {
        this.randomizedContactSelection = null;
    }

    /**
     * Gets the value of the agentSelectionScore property.
     * 
     * @return
     *     possible object is
     *     {@link AgentSelectionScore }
     *     
     */
    public AgentSelectionScore getAgentSelectionScore() {
        if (agentSelectionScore == null) {
            return AgentSelectionScore.LONGESTIDLETIME;
        } else {
            return agentSelectionScore;
        }
    }

    /**
     * Sets the value of the agentSelectionScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentSelectionScore }
     *     
     */
    public void setAgentSelectionScore(AgentSelectionScore value) {
        this.agentSelectionScore = value;
    }

    public boolean isSetAgentSelectionScore() {
        return (this.agentSelectionScore!= null);
    }

    /**
     * Gets the value of the contactSelectionScore property.
     * 
     * @return
     *     possible object is
     *     {@link ContactSelectionScore }
     *     
     */
    public ContactSelectionScore getContactSelectionScore() {
        if (contactSelectionScore == null) {
            return ContactSelectionScore.LONGESTWAITINGTIME;
        } else {
            return contactSelectionScore;
        }
    }

    /**
     * Sets the value of the contactSelectionScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactSelectionScore }
     *     
     */
    public void setContactSelectionScore(ContactSelectionScore value) {
        this.contactSelectionScore = value;
    }

    public boolean isSetContactSelectionScore() {
        return (this.contactSelectionScore!= null);
    }

}
