//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                   Defines a shift in the schedule of an agent group.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduleShiftParams", propOrder = {
    "shiftParts",
    "numAgentsData"
})
public class ScheduleShiftParams {

    @XmlElement(name = "shiftPart")
    protected List<ShiftPartParams> shiftParts;
    @XmlList
    @XmlElement(type = Integer.class)
    protected int[] numAgentsData;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "xref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object xref;
    @XmlAttribute(name = "numAgents")
    protected Integer numAgents;
    @XmlAttribute(name = "probAgents")
    protected Double probAgents;

    /**
     * Gets the value of the shiftParts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shiftParts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShiftParts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShiftPartParams }
     * 
     * 
     */
    public List<ShiftPartParams> getShiftParts() {
        if (shiftParts == null) {
            shiftParts = new ArrayList<ShiftPartParams>();
        }
        return this.shiftParts;
    }

    public boolean isSetShiftParts() {
        return ((this.shiftParts!= null)&&(!this.shiftParts.isEmpty()));
    }

    public void unsetShiftParts() {
        this.shiftParts = null;
    }

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Integer }
     *     
     */
    public int[] getNumAgentsData() {
        if (this.numAgentsData == null) {
            return new int[ 0 ] ;
        }
        int[] retVal = new int[this.numAgentsData.length] ;
        System.arraycopy(this.numAgentsData, 0, retVal, 0, this.numAgentsData.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Integer }
     *     
     */
    public int getNumAgentsData(int idx) {
        if (this.numAgentsData == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.numAgentsData[idx];
    }

    public int getNumAgentsDataLength() {
        if (this.numAgentsData == null) {
            return  0;
        }
        return this.numAgentsData.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Integer }
     *     
     */
    public void setNumAgentsData(int[] values) {
        int len = values.length;
        this.numAgentsData = ((int[]) new int[len] );
        for (int i = 0; (i<len); i ++) {
            this.numAgentsData[i] = new Integer(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public int setNumAgentsData(int idx, int value) {
        return this.numAgentsData[idx] = new Integer(value);
    }

    public boolean isSetNumAgentsData() {
        return ((this.numAgentsData!= null)&&(this.numAgentsData.length > 0));
    }

    public void unsetNumAgentsData() {
        this.numAgentsData = null;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the xref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getXref() {
        return xref;
    }

    /**
     * Sets the value of the xref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setXref(Object value) {
        this.xref = value;
    }

    public boolean isSetXref() {
        return (this.xref!= null);
    }

    /**
     * Gets the value of the numAgents property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumAgents() {
        if (numAgents == null) {
            return  0;
        } else {
            return numAgents;
        }
    }

    /**
     * Sets the value of the numAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumAgents(int value) {
        this.numAgents = value;
    }

    public boolean isSetNumAgents() {
        return (this.numAgents!= null);
    }

    public void unsetNumAgents() {
        this.numAgents = null;
    }

    /**
     * Gets the value of the probAgents property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getProbAgents() {
        if (probAgents == null) {
            return  1.0D;
        } else {
            return probAgents;
        }
    }

    /**
     * Sets the value of the probAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setProbAgents(double value) {
        this.probAgents = value;
    }

    public boolean isSetProbAgents() {
        return (this.probAgents!= null);
    }

    public void unsetProbAgents() {
        this.probAgents = null;
    }

}
