//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import umontreal.iro.lecuyer.xmlbind.params.IntArray;


/**
 * 
 *             Determines the starting condition of the queues and agents.
 *             This parameter requires the waiting queue to be associated with the call types.
 *             There must be one waiting queue per call type.
 *             The user specifies the number of calls of each type being served by each
 *             agent group, and also the number of calls in each waiting queue.
 *             All these calls will be counted in the performance measures.
 *             
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns="http://www.w3.org/1999/xhtml" xmlns:cc="http://www.iro.umontreal.ca/lecuyer/contactcenters" xmlns:ccapp="http://www.iro.umontreal.ca/lecuyer/contactcenters/app" xmlns:ccmsk="http://www.iro.umontreal.ca/lecuyer/contactcenters/msk" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:ssj="http://www.iro.umontreal.ca/lecuyer/ssj" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 *             Because of the complexity of the simulator, we imposed some limitations in the implementations.
 *             All starting calls will arrive at simulation time 0.
 *             Even though the user can input the waited and served times that occured before the 
 *             simulation, these time durations will only be used to generate the remaining patience
 *             and service times. 
 *             &lt;/p&gt;
 * </pre>
 * 
 *             
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns="http://www.w3.org/1999/xhtml" xmlns:cc="http://www.iro.umontreal.ca/lecuyer/contactcenters" xmlns:ccapp="http://www.iro.umontreal.ca/lecuyer/contactcenters/app" xmlns:ccmsk="http://www.iro.umontreal.ca/lecuyer/contactcenters/msk" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:ssj="http://www.iro.umontreal.ca/lecuyer/ssj" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 *                Note that to use this parameter: the call center simulator must use &lt;tt&gt;RepLogic&lt;/tt&gt;
 *                from the package &lt;tt&gt;umontreal.iro.lecuyer.contactcenters.msk.simlogic&lt;/tt&gt;.
 *                Otherwise, this parameter will have no effect.
 *             &lt;/p&gt;
 * </pre>
 * 
 *          
 * 
 * <p>Java class for StartingStateParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StartingStateParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="queueSizes" type="{http://www.iro.umontreal.ca/lecuyer/ssj}intList"/>
 *           &lt;element name="detailedQueueState" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}DetailedStartingQueueState" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="callByGroup" type="{http://www.iro.umontreal.ca/lecuyer/ssj}IntArray"/>
 *           &lt;element name="detailedGroupState" type="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}DetailedStartingGroupState" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartingStateParams", propOrder = {
    "queueSizes",
    "detailedQueueState",
    "callByGroup",
    "detailedGroupState"
})
public class StartingStateParams {

    @XmlList
    @XmlElement(type = Integer.class)
    protected List<Integer> queueSizes;
    protected List<DetailedStartingQueueState> detailedQueueState;
    protected IntArray callByGroup;
    protected List<DetailedStartingGroupState> detailedGroupState;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;

    /**
     * Gets the value of the queueSizes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queueSizes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueueSizes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getQueueSizes() {
        if (queueSizes == null) {
            queueSizes = new ArrayList<Integer>();
        }
        return this.queueSizes;
    }

    public boolean isSetQueueSizes() {
        return ((this.queueSizes!= null)&&(!this.queueSizes.isEmpty()));
    }

    public void unsetQueueSizes() {
        this.queueSizes = null;
    }

    /**
     * Gets the value of the detailedQueueState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detailedQueueState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetailedQueueState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetailedStartingQueueState }
     * 
     * 
     */
    public List<DetailedStartingQueueState> getDetailedQueueState() {
        if (detailedQueueState == null) {
            detailedQueueState = new ArrayList<DetailedStartingQueueState>();
        }
        return this.detailedQueueState;
    }

    public boolean isSetDetailedQueueState() {
        return ((this.detailedQueueState!= null)&&(!this.detailedQueueState.isEmpty()));
    }

    public void unsetDetailedQueueState() {
        this.detailedQueueState = null;
    }

    /**
     * Gets the value of the callByGroup property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getCallByGroup() {
        return callByGroup;
    }

    /**
     * Sets the value of the callByGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setCallByGroup(IntArray value) {
        this.callByGroup = value;
    }

    public boolean isSetCallByGroup() {
        return (this.callByGroup!= null);
    }

    /**
     * Gets the value of the detailedGroupState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detailedGroupState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetailedGroupState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetailedStartingGroupState }
     * 
     * 
     */
    public List<DetailedStartingGroupState> getDetailedGroupState() {
        if (detailedGroupState == null) {
            detailedGroupState = new ArrayList<DetailedStartingGroupState>();
        }
        return this.detailedGroupState;
    }

    public boolean isSetDetailedGroupState() {
        return ((this.detailedGroupState!= null)&&(!this.detailedGroupState.isEmpty()));
    }

    public void unsetDetailedGroupState() {
        this.detailedGroupState = null;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnabled() {
        if (enabled == null) {
            return true;
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    public boolean isSetEnabled() {
        return (this.enabled!= null);
    }

    public void unsetEnabled() {
        this.enabled = null;
    }

}
