//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.msk.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *    Contains the parameters for a condition comparing
 *    two index quantities possibly for
 *    specific call types.
 *    
 * 
 * <p>Java class for TwoIndicesWithTypesParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwoIndicesWithTypesParams">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iro.umontreal.ca/lecuyer/contactcenters/msk}TwoIndicesParams">
 *       &lt;attribute name="firstType" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeInt" />
 *       &lt;attribute name="secondType" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwoIndicesWithTypesParams")
public class TwoIndicesWithTypesParams
    extends TwoIndicesParams
{

    @XmlAttribute(name = "firstType")
    protected Integer firstType;
    @XmlAttribute(name = "secondType")
    protected Integer secondType;

    /**
     * Gets the value of the firstType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getFirstType() {
        return firstType;
    }

    /**
     * Sets the value of the firstType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFirstType(int value) {
        this.firstType = value;
    }

    public boolean isSetFirstType() {
        return (this.firstType!= null);
    }

    public void unsetFirstType() {
        this.firstType = null;
    }

    /**
     * Gets the value of the secondType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSecondType() {
        return secondType;
    }

    /**
     * Sets the value of the secondType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSecondType(int value) {
        this.secondType = value;
    }

    public boolean isSetSecondType() {
        return (this.secondType!= null);
    }

    public void unsetSecondType() {
        this.secondType = null;
    }

}
