//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.xmlbind.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import umontreal.iro.lecuyer.contactcenters.msk.params.AgentGroupParams;
import umontreal.iro.lecuyer.contactcenters.msk.params.AgentParams;
import umontreal.iro.lecuyer.contactcenters.msk.params.CallSourceParams;
import umontreal.iro.lecuyer.contactcenters.msk.params.CallTypeParams;
import umontreal.iro.lecuyer.contactcenters.msk.params.SegmentParams;


/**
 * 
 *                   Represents an entity with a name and zero or several
 *                   properties.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Named", propOrder = {
    "properties"
})
@XmlSeeAlso({
    SegmentParams.class,
    AgentParams.class,
    CallTypeParams.class,
    AgentGroupParams.class,
    CallSourceParams.class
})
public class Named {

    protected PropertiesParams properties;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesParams }
     *     
     */
    public PropertiesParams getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesParams }
     *     
     */
    public void setProperties(PropertiesParams value) {
        this.properties = value;
    }

    public boolean isSetProperties() {
        return (this.properties!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

}
