//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.xmlbind.params;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the umontreal.iro.lecuyer.xmlbind.params package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: umontreal.iro.lecuyer.xmlbind.params
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DurationArray }
     * 
     */
    public DurationArray createDurationArray() {
        return new DurationArray();
    }

    /**
     * Create an instance of {@link NonNegativeDurationArray }
     * 
     */
    public NonNegativeDurationArray createNonNegativeDurationArray() {
        return new NonNegativeDurationArray();
    }

    /**
     * Create an instance of {@link DoubleArray }
     * 
     */
    public DoubleArray createDoubleArray() {
        return new DoubleArray();
    }

    /**
     * Create an instance of {@link IntArray }
     * 
     */
    public IntArray createIntArray() {
        return new IntArray();
    }

    /**
     * Create an instance of {@link BooleanArray }
     * 
     */
    public BooleanArray createBooleanArray() {
        return new BooleanArray();
    }

    /**
     * Create an instance of {@link DurationProperty }
     * 
     */
    public DurationProperty createDurationProperty() {
        return new DurationProperty();
    }

    /**
     * Create an instance of {@link StringListProperty }
     * 
     */
    public StringListProperty createStringListProperty() {
        return new StringListProperty();
    }

    /**
     * Create an instance of {@link DurationListProperty }
     * 
     */
    public DurationListProperty createDurationListProperty() {
        return new DurationListProperty();
    }

    /**
     * Create an instance of {@link NumberProperty }
     * 
     */
    public NumberProperty createNumberProperty() {
        return new NumberProperty();
    }

    /**
     * Create an instance of {@link NumberListProperty }
     * 
     */
    public NumberListProperty createNumberListProperty() {
        return new NumberListProperty();
    }

    /**
     * Create an instance of {@link DateTimeProperty }
     * 
     */
    public DateTimeProperty createDateTimeProperty() {
        return new DateTimeProperty();
    }

    /**
     * Create an instance of {@link BooleanArrayProperty }
     * 
     */
    public BooleanArrayProperty createBooleanArrayProperty() {
        return new BooleanArrayProperty();
    }

    /**
     * Create an instance of {@link BooleanListProperty }
     * 
     */
    public BooleanListProperty createBooleanListProperty() {
        return new BooleanListProperty();
    }

    /**
     * Create an instance of {@link NumberArrayProperty }
     * 
     */
    public NumberArrayProperty createNumberArrayProperty() {
        return new NumberArrayProperty();
    }

    /**
     * Create an instance of {@link StringProperty }
     * 
     */
    public StringProperty createStringProperty() {
        return new StringProperty();
    }

    /**
     * Create an instance of {@link IntegerListProperty }
     * 
     */
    public IntegerListProperty createIntegerListProperty() {
        return new IntegerListProperty();
    }

    /**
     * Create an instance of {@link DBConnectionParams }
     * 
     */
    public DBConnectionParams createDBConnectionParams() {
        return new DBConnectionParams();
    }

    /**
     * Create an instance of {@link PropertiesParams }
     * 
     */
    public PropertiesParams createPropertiesParams() {
        return new PropertiesParams();
    }

    /**
     * Create an instance of {@link IntegerArrayProperty }
     * 
     */
    public IntegerArrayProperty createIntegerArrayProperty() {
        return new IntegerArrayProperty();
    }

    /**
     * Create an instance of {@link IntegerProperty }
     * 
     */
    public IntegerProperty createIntegerProperty() {
        return new IntegerProperty();
    }

    /**
     * Create an instance of {@link Named }
     * 
     */
    public Named createNamed() {
        return new Named();
    }

    /**
     * Create an instance of {@link BooleanProperty }
     * 
     */
    public BooleanProperty createBooleanProperty() {
        return new BooleanProperty();
    }

    /**
     * Create an instance of {@link RandomVariateGenParams }
     * 
     */
    public RandomVariateGenParams createRandomVariateGenParams() {
        return new RandomVariateGenParams();
    }

    /**
     * Create an instance of {@link DurationArray.Row }
     * 
     */
    public DurationArray.Row createDurationArrayRow() {
        return new DurationArray.Row();
    }

    /**
     * Create an instance of {@link NonNegativeDurationArray.Row }
     * 
     */
    public NonNegativeDurationArray.Row createNonNegativeDurationArrayRow() {
        return new NonNegativeDurationArray.Row();
    }

    /**
     * Create an instance of {@link DoubleArray.Row }
     * 
     */
    public DoubleArray.Row createDoubleArrayRow() {
        return new DoubleArray.Row();
    }

    /**
     * Create an instance of {@link IntArray.Row }
     * 
     */
    public IntArray.Row createIntArrayRow() {
        return new IntArray.Row();
    }

    /**
     * Create an instance of {@link BooleanArray.Row }
     * 
     */
    public BooleanArray.Row createBooleanArrayRow() {
        return new BooleanArray.Row();
    }

}
