//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iro.umontreal.ca/lecuyer/ssj")
package umontreal.iro.lecuyer.xmlbind.params;
