//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.xmlbind.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   Represents a set of properties associated with some
 *                   entity.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertiesParams", propOrder = {
    "propertyList"
})
public class PropertiesParams {

    @XmlElements({
        @XmlElement(name = "boolean", type = BooleanProperty.class),
        @XmlElement(name = "string", type = StringProperty.class),
        @XmlElement(name = "integer", type = IntegerProperty.class),
        @XmlElement(name = "number", type = NumberProperty.class),
        @XmlElement(name = "duration", type = DurationProperty.class),
        @XmlElement(name = "dateTime", type = DateTimeProperty.class),
        @XmlElement(name = "booleanList", type = BooleanListProperty.class),
        @XmlElement(name = "booleanArray", type = BooleanArrayProperty.class),
        @XmlElement(name = "stringList", type = StringListProperty.class),
        @XmlElement(name = "integerList", type = IntegerListProperty.class),
        @XmlElement(name = "integerArray", type = IntegerArrayProperty.class),
        @XmlElement(name = "numberList", type = NumberListProperty.class),
        @XmlElement(name = "numberArray", type = NumberArrayProperty.class),
        @XmlElement(name = "durationList", type = DurationListProperty.class)
    })
    protected List<AbstractProperty> propertyList;

    /**
     * Gets the value of the propertyList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BooleanProperty }
     * {@link StringProperty }
     * {@link IntegerProperty }
     * {@link NumberProperty }
     * {@link DurationProperty }
     * {@link DateTimeProperty }
     * {@link BooleanListProperty }
     * {@link BooleanArrayProperty }
     * {@link StringListProperty }
     * {@link IntegerListProperty }
     * {@link IntegerArrayProperty }
     * {@link NumberListProperty }
     * {@link NumberArrayProperty }
     * {@link DurationListProperty }
     * 
     * 
     */
    public List<AbstractProperty> getPropertyList() {
        if (propertyList == null) {
            propertyList = new ArrayList<AbstractProperty>();
        }
        return this.propertyList;
    }

    public boolean isSetPropertyList() {
        return ((this.propertyList!= null)&&(!this.propertyList.isEmpty()));
    }

    public void unsetPropertyList() {
        this.propertyList = null;
    }

}
