//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.xmlbind.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   Represents a property whose value is a list of
 *                   strings.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StringListProperty", propOrder = {
    "value"
})
public class StringListProperty
    extends AbstractProperty
{

    @XmlList
    @XmlElement(required = true)
    protected String[] value;

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link String }
     *     
     */
    public String[] getValue() {
        if (this.value == null) {
            return new String[ 0 ] ;
        }
        String[] retVal = new String[this.value.length] ;
        System.arraycopy(this.value, 0, retVal, 0, this.value.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link String }
     *     
     */
    public String getValue(int idx) {
        if (this.value == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.value[idx];
    }

    public int getValueLength() {
        if (this.value == null) {
            return  0;
        }
        return this.value.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link String }
     *     
     */
    public void setValue(String[] values) {
        int len = values.length;
        this.value = ((String[]) new String[len] );
        for (int i = 0; (i<len); i ++) {
            this.value[i] = values[i];
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public String setValue(int idx, String value) {
        return this.value[idx] = value;
    }

    public boolean isSetValue() {
        return ((this.value!= null)&&(this.value.length > 0));
    }

    public void unsetValue() {
        this.value = null;
    }

}
