//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.app.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                Determine the parameters for a histogram.
 *               
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistogramParams")
public class HistogramParams {

    @XmlAttribute(name = "syncTicks")
    protected Boolean syncTicks;
    @XmlAttribute(name = "numBins")
    protected Integer numBins;
    @XmlAttribute(name = "leftBoundary")
    protected Double leftBoundary;
    @XmlAttribute(name = "rightBoundary")
    protected Double rightBoundary;

    /**
     * Gets the value of the syncTicks property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSyncTicks() {
        if (syncTicks == null) {
            return false;
        } else {
            return syncTicks;
        }
    }

    /**
     * Sets the value of the syncTicks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSyncTicks(boolean value) {
        this.syncTicks = value;
    }

    public boolean isSetSyncTicks() {
        return (this.syncTicks!= null);
    }

    public void unsetSyncTicks() {
        this.syncTicks = null;
    }

    /**
     * Gets the value of the numBins property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumBins() {
        return numBins;
    }

    /**
     * Sets the value of the numBins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumBins(int value) {
        this.numBins = value;
    }

    public boolean isSetNumBins() {
        return (this.numBins!= null);
    }

    public void unsetNumBins() {
        this.numBins = null;
    }

    /**
     * Gets the value of the leftBoundary property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getLeftBoundary() {
        return leftBoundary;
    }

    /**
     * Sets the value of the leftBoundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLeftBoundary(double value) {
        this.leftBoundary = value;
    }

    public boolean isSetLeftBoundary() {
        return (this.leftBoundary!= null);
    }

    public void unsetLeftBoundary() {
        this.leftBoundary = null;
    }

    /**
     * Gets the value of the rightBoundary property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getRightBoundary() {
        return rightBoundary;
    }

    /**
     * Sets the value of the rightBoundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRightBoundary(double value) {
        this.rightBoundary = value;
    }

    public boolean isSetRightBoundary() {
        return (this.rightBoundary!= null);
    }

    public void unsetRightBoundary() {
        this.rightBoundary = null;
    }

}
