//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.app.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 *                   Represents a matrix of observations concerning a
 *                   specific type of performance measure.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObsMatrix", propOrder = {
    "obs"
})
public class ObsMatrix {

    protected List<ObsMatrix.Obs> obs;
    @XmlAttribute(name = "measure", required = true)
    protected String measure;

    /**
     * Gets the value of the obs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObsMatrix.Obs }
     * 
     * 
     */
    public List<ObsMatrix.Obs> getObs() {
        if (obs == null) {
            obs = new ArrayList<ObsMatrix.Obs>();
        }
        return this.obs;
    }

    public boolean isSetObs() {
        return ((this.obs!= null)&&(!this.obs.isEmpty()));
    }

    public void unsetObs() {
        this.obs = null;
    }

    /**
     * Gets the value of the measure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasure(String value) {
        this.measure = value;
    }

    public boolean isSetMeasure() {
        return (this.measure!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.iro.umontreal.ca/lecuyer/ssj>doubleList">
     *       &lt;attribute name="row" use="required" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeInt" />
     *       &lt;attribute name="column" use="required" type="{http://www.iro.umontreal.ca/lecuyer/ssj}nonNegativeInt" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Obs {

        @XmlValue
        protected List<Double> value;
        @XmlAttribute(name = "row", required = true)
        protected int row;
        @XmlAttribute(name = "column", required = true)
        protected int column;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getValue() {
            if (value == null) {
                value = new ArrayList<Double>();
            }
            return this.value;
        }

        public boolean isSetValue() {
            return ((this.value!= null)&&(!this.value.isEmpty()));
        }

        public void unsetValue() {
            this.value = null;
        }

        /**
         * Gets the value of the row property.
         * 
         */
        public int getRow() {
            return row;
        }

        /**
         * Sets the value of the row property.
         * 
         */
        public void setRow(int value) {
            this.row = value;
        }

        public boolean isSetRow() {
            return true;
        }

        /**
         * Gets the value of the column property.
         * 
         */
        public int getColumn() {
            return column;
        }

        /**
         * Sets the value of the column property.
         * 
         */
        public void setColumn(int value) {
            this.column = value;
        }

        public boolean isSetColumn() {
            return true;
        }

    }

}
