//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.app.params;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerPeriodCollectingMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PerPeriodCollectingMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PERIODOFENTRY"/>
 *     &lt;enumeration value="PERIODOFEXIT"/>
 *     &lt;enumeration value="PERIODOFBEGINSERVICEORENTRY"/>
 *     &lt;enumeration value="PERIODOFBEGINSERVICEOREXIT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PerPeriodCollectingMode")
@XmlEnum
public enum PerPeriodCollectingMode {


    /**
     * 
     *                   All events concerning a contact are counted in the
     *                   period of its arrival in the system.
     *                
     * 
     */
    PERIODOFENTRY,

    /**
     * 
     *                   All events concerning a contact are counted in the
     *                   period of its exit (end of service, abandonment, or
     *                   blocking).
     *                
     * 
     */
    PERIODOFEXIT,

    /**
     * 
     *                   All events concerning a contact are counted in the
     *                   period at which the service begins. Events concerning
     *                   unserved contacts are counted in the period of
     *                   arrival.
     *                
     * 
     */
    PERIODOFBEGINSERVICEORENTRY,

    /**
     * 
     *                   All events concerning a contact are counted in the
     *                   period at which the service begins. Events concerning
     *                   unserved contacts are counted in the period of exit
     *                   (abandonment or blocking).
     *                
     * 
     */
    PERIODOFBEGINSERVICEOREXIT;

    public String value() {
        return name();
    }

    public static PerPeriodCollectingMode fromValue(String v) {
        return valueOf(v);
    }

}
