//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.app.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   Represents parameters for a contact center simulation
 *                   using independent replications to evaluate performance
 *                   measures for a finite horizon and possibly
 *                   non-stationary system.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepSimParams", propOrder = {
    "outReplications"
})
@XmlSeeAlso({
    StratSimParams.class,
    CTMCRepSimParams.class
})
public class RepSimParams
    extends SimParams
{

    @XmlList
    @XmlElement(type = Integer.class)
    protected int[] outReplications;
    @XmlAttribute(name = "minReplications", required = true)
    protected int minReplications;
    @XmlAttribute(name = "maxReplications")
    protected Integer maxReplications;
    @XmlAttribute(name = "perPeriodCollectingMode")
    protected PerPeriodCollectingMode perPeriodCollectingMode;

    /**
     * 
     * 
     * @return
     *     array of
     *     {@link Integer }
     *     
     */
    public int[] getOutReplications() {
        if (this.outReplications == null) {
            return new int[ 0 ] ;
        }
        int[] retVal = new int[this.outReplications.length] ;
        System.arraycopy(this.outReplications, 0, retVal, 0, this.outReplications.length);
        return (retVal);
    }

    /**
     * 
     * 
     * @return
     *     one of
     *     {@link Integer }
     *     
     */
    public int getOutReplications(int idx) {
        if (this.outReplications == null) {
            throw new IndexOutOfBoundsException();
        }
        return this.outReplications[idx];
    }

    public int getOutReplicationsLength() {
        if (this.outReplications == null) {
            return  0;
        }
        return this.outReplications.length;
    }

    /**
     * 
     * 
     * @param values
     *     allowed objects are
     *     {@link Integer }
     *     
     */
    public void setOutReplications(int[] values) {
        int len = values.length;
        this.outReplications = ((int[]) new int[len] );
        for (int i = 0; (i<len); i ++) {
            this.outReplications[i] = new Integer(values[i]);
        }
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public int setOutReplications(int idx, int value) {
        return this.outReplications[idx] = new Integer(value);
    }

    public boolean isSetOutReplications() {
        return ((this.outReplications!= null)&&(this.outReplications.length > 0));
    }

    public void unsetOutReplications() {
        this.outReplications = null;
    }

    /**
     * Gets the value of the minReplications property.
     * 
     */
    public int getMinReplications() {
        return minReplications;
    }

    /**
     * Sets the value of the minReplications property.
     * 
     */
    public void setMinReplications(int value) {
        this.minReplications = value;
    }

    public boolean isSetMinReplications() {
        return true;
    }

    /**
     * Gets the value of the maxReplications property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxReplications() {
        return maxReplications;
    }

    /**
     * Sets the value of the maxReplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxReplications(int value) {
        this.maxReplications = value;
    }

    public boolean isSetMaxReplications() {
        return (this.maxReplications!= null);
    }

    public void unsetMaxReplications() {
        this.maxReplications = null;
    }

    /**
     * Gets the value of the perPeriodCollectingMode property.
     * 
     * @return
     *     possible object is
     *     {@link PerPeriodCollectingMode }
     *     
     */
    public PerPeriodCollectingMode getPerPeriodCollectingMode() {
        if (perPeriodCollectingMode == null) {
            return PerPeriodCollectingMode.PERIODOFENTRY;
        } else {
            return perPeriodCollectingMode;
        }
    }

    /**
     * Sets the value of the perPeriodCollectingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerPeriodCollectingMode }
     *     
     */
    public void setPerPeriodCollectingMode(PerPeriodCollectingMode value) {
        this.perPeriodCollectingMode = value;
    }

    public boolean isSetPerPeriodCollectingMode() {
        return (this.perPeriodCollectingMode!= null);
    }

}
