//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.app.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   Defines parameters for sequential sampling based on
 *                   some type of performance measure.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SequentialSamplingParams")
public class SequentialSamplingParams {

    @XmlAttribute(name = "measure", required = true)
    protected String measure;
    @XmlAttribute(name = "targetError", required = true)
    protected double targetError;
    @XmlAttribute(name = "confidenceLevel", required = true)
    protected double confidenceLevel;
    @XmlAttribute(name = "globalOnly")
    protected Boolean globalOnly;

    /**
     * Gets the value of the measure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasure(String value) {
        this.measure = value;
    }

    public boolean isSetMeasure() {
        return (this.measure!= null);
    }

    /**
     * Gets the value of the targetError property.
     * 
     */
    public double getTargetError() {
        return targetError;
    }

    /**
     * Sets the value of the targetError property.
     * 
     */
    public void setTargetError(double value) {
        this.targetError = value;
    }

    public boolean isSetTargetError() {
        return true;
    }

    /**
     * Gets the value of the confidenceLevel property.
     * 
     */
    public double getConfidenceLevel() {
        return confidenceLevel;
    }

    /**
     * Sets the value of the confidenceLevel property.
     * 
     */
    public void setConfidenceLevel(double value) {
        this.confidenceLevel = value;
    }

    public boolean isSetConfidenceLevel() {
        return true;
    }

    /**
     * Gets the value of the globalOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGlobalOnly() {
        if (globalOnly == null) {
            return false;
        } else {
            return globalOnly;
        }
    }

    /**
     * Sets the value of the globalOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGlobalOnly(boolean value) {
        this.globalOnly = value;
    }

    public boolean isSetGlobalOnly() {
        return (this.globalOnly!= null);
    }

    public void unsetGlobalOnly() {
        this.globalOnly = null;
    }

}
