//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.25 at 06:40:43 PM SGT 
//


package umontreal.iro.lecuyer.contactcenters.app.params;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   Represents parameters specific to an experiment using
 *                   independent replications and stratification.
 *                
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StratSimParams")
public class StratSimParams
    extends RepSimParams
{

    @XmlAttribute(name = "numStrata", required = true)
    protected int numStrata;
    @XmlAttribute(name = "numPilotRunsPerStratum")
    protected Integer numPilotRunsPerStratum;
    @XmlAttribute(name = "selectedPerformanceMeasure")
    protected String selectedPerformanceMeasure;
    @XmlAttribute(name = "selectedRow")
    protected Integer selectedRow;
    @XmlAttribute(name = "selectedColumn")
    protected Integer selectedColumn;
    @XmlAttribute(name = "stratificationVariable")
    protected String stratificationVariable;
    @XmlAttribute(name = "optimalAllocation")
    protected Boolean optimalAllocation;

    /**
     * Gets the value of the numStrata property.
     * 
     */
    public int getNumStrata() {
        return numStrata;
    }

    /**
     * Sets the value of the numStrata property.
     * 
     */
    public void setNumStrata(int value) {
        this.numStrata = value;
    }

    public boolean isSetNumStrata() {
        return true;
    }

    /**
     * Gets the value of the numPilotRunsPerStratum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getNumPilotRunsPerStratum() {
        if (numPilotRunsPerStratum == null) {
            return  200;
        } else {
            return numPilotRunsPerStratum;
        }
    }

    /**
     * Sets the value of the numPilotRunsPerStratum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumPilotRunsPerStratum(int value) {
        this.numPilotRunsPerStratum = value;
    }

    public boolean isSetNumPilotRunsPerStratum() {
        return (this.numPilotRunsPerStratum!= null);
    }

    public void unsetNumPilotRunsPerStratum() {
        this.numPilotRunsPerStratum = null;
    }

    /**
     * Gets the value of the selectedPerformanceMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedPerformanceMeasure() {
        return selectedPerformanceMeasure;
    }

    /**
     * Sets the value of the selectedPerformanceMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedPerformanceMeasure(String value) {
        this.selectedPerformanceMeasure = value;
    }

    public boolean isSetSelectedPerformanceMeasure() {
        return (this.selectedPerformanceMeasure!= null);
    }

    /**
     * Gets the value of the selectedRow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSelectedRow() {
        return selectedRow;
    }

    /**
     * Sets the value of the selectedRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSelectedRow(int value) {
        this.selectedRow = value;
    }

    public boolean isSetSelectedRow() {
        return (this.selectedRow!= null);
    }

    public void unsetSelectedRow() {
        this.selectedRow = null;
    }

    /**
     * Gets the value of the selectedColumn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSelectedColumn() {
        return selectedColumn;
    }

    /**
     * Sets the value of the selectedColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSelectedColumn(int value) {
        this.selectedColumn = value;
    }

    public boolean isSetSelectedColumn() {
        return (this.selectedColumn!= null);
    }

    public void unsetSelectedColumn() {
        this.selectedColumn = null;
    }

    /**
     * Gets the value of the stratificationVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStratificationVariable() {
        return stratificationVariable;
    }

    /**
     * Sets the value of the stratificationVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStratificationVariable(String value) {
        this.stratificationVariable = value;
    }

    public boolean isSetStratificationVariable() {
        return (this.stratificationVariable!= null);
    }

    /**
     * Gets the value of the optimalAllocation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOptimalAllocation() {
        if (optimalAllocation == null) {
            return false;
        } else {
            return optimalAllocation;
        }
    }

    /**
     * Sets the value of the optimalAllocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptimalAllocation(boolean value) {
        this.optimalAllocation = value;
    }

    public boolean isSetOptimalAllocation() {
        return (this.optimalAllocation!= null);
    }

    public void unsetOptimalAllocation() {
        this.optimalAllocation = null;
    }

}
